// Mocks generated by Mockito 5.4.6 from annotations
// in pak_connect/test/core/services/media_send_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:pak_connect/domain/entities/queued_message.dart' as _i8;
import 'package:pak_connect/domain/interfaces/i_mesh_networking_service.dart'
    as _i3;
import 'package:pak_connect/domain/messaging/queue_sync_manager.dart' as _i6;
import 'package:pak_connect/domain/models/mesh_network_models.dart' as _i2;
import 'package:pak_connect/domain/models/mesh_relay_models.dart' as _i5;
import 'package:pak_connect/domain/services/mesh_networking_service.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMeshSendResult_0 extends _i1.SmartFake
    implements _i2.MeshSendResult {
  _FakeMeshSendResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMeshNetworkStatistics_1 extends _i1.SmartFake
    implements _i2.MeshNetworkStatistics {
  _FakeMeshNetworkStatistics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IMeshNetworkingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMeshNetworkingService extends _i1.Mock
    implements _i3.IMeshNetworkingService {
  MockIMeshNetworkingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.MeshNetworkStatus> get meshStatus =>
      (super.noSuchMethod(
            Invocation.getter(#meshStatus),
            returnValue: _i4.Stream<_i2.MeshNetworkStatus>.empty(),
          )
          as _i4.Stream<_i2.MeshNetworkStatus>);

  @override
  _i4.Stream<_i5.RelayStatistics> get relayStats =>
      (super.noSuchMethod(
            Invocation.getter(#relayStats),
            returnValue: _i4.Stream<_i5.RelayStatistics>.empty(),
          )
          as _i4.Stream<_i5.RelayStatistics>);

  @override
  _i4.Stream<_i6.QueueSyncManagerStats> get queueStats =>
      (super.noSuchMethod(
            Invocation.getter(#queueStats),
            returnValue: _i4.Stream<_i6.QueueSyncManagerStats>.empty(),
          )
          as _i4.Stream<_i6.QueueSyncManagerStats>);

  @override
  _i4.Stream<String> get messageDeliveryStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageDeliveryStream),
            returnValue: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  _i4.Stream<_i7.ReceivedBinaryEvent> get binaryPayloadStream =>
      (super.noSuchMethod(
            Invocation.getter(#binaryPayloadStream),
            returnValue: _i4.Stream<_i7.ReceivedBinaryEvent>.empty(),
          )
          as _i4.Stream<_i7.ReceivedBinaryEvent>);

  @override
  _i4.Future<void> initialize({String? nodeId}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {#nodeId: nodeId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.MeshSendResult> sendMeshMessage({
    required String? content,
    required String? recipientPublicKey,
    _i8.MessagePriority? priority = _i8.MessagePriority.normal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMeshMessage, [], {
              #content: content,
              #recipientPublicKey: recipientPublicKey,
              #priority: priority,
            }),
            returnValue: _i4.Future<_i2.MeshSendResult>.value(
              _FakeMeshSendResult_0(
                this,
                Invocation.method(#sendMeshMessage, [], {
                  #content: content,
                  #recipientPublicKey: recipientPublicKey,
                  #priority: priority,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.MeshSendResult>);

  @override
  _i4.Future<String> sendBinaryMedia({
    required _i9.Uint8List? data,
    required String? recipientId,
    int? originalType = 144,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendBinaryMedia, [], {
              #data: data,
              #recipientId: recipientId,
              #originalType: originalType,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#sendBinaryMedia, [], {
                  #data: data,
                  #recipientId: recipientId,
                  #originalType: originalType,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> retryBinaryMedia({
    required String? transferId,
    String? recipientId,
    int? originalType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#retryBinaryMedia, [], {
              #transferId: transferId,
              #recipientId: recipientId,
              #originalType: originalType,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, _i6.QueueSyncResult>> syncQueuesWithPeers() =>
      (super.noSuchMethod(
            Invocation.method(#syncQueuesWithPeers, []),
            returnValue: _i4.Future<Map<String, _i6.QueueSyncResult>>.value(
              <String, _i6.QueueSyncResult>{},
            ),
          )
          as _i4.Future<Map<String, _i6.QueueSyncResult>>);

  @override
  _i4.Future<bool> retryMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#retryMessage, [messageId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMessage, [messageId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setPriority(
    String? messageId,
    _i8.MessagePriority? priority,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setPriority, [messageId, priority]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> retryAllMessages() =>
      (super.noSuchMethod(
            Invocation.method(#retryAllMessages, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  List<_i8.QueuedMessage> getQueuedMessagesForChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getQueuedMessagesForChat, [chatId]),
            returnValue: <_i8.QueuedMessage>[],
          )
          as List<_i8.QueuedMessage>);

  @override
  List<_i7.PendingBinaryTransfer> getPendingBinaryTransfers() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingBinaryTransfers, []),
            returnValue: <_i7.PendingBinaryTransfer>[],
          )
          as List<_i7.PendingBinaryTransfer>);

  @override
  _i2.MeshNetworkStatistics getNetworkStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getNetworkStatistics, []),
            returnValue: _FakeMeshNetworkStatistics_1(
              this,
              Invocation.method(#getNetworkStatistics, []),
            ),
          )
          as _i2.MeshNetworkStatistics);

  @override
  void refreshMeshStatus() => super.noSuchMethod(
    Invocation.method(#refreshMeshStatus, []),
    returnValueForMissingStub: null,
  );
}
