// Mocks generated by Mockito 5.4.6 from annotations
// in pak_connect/test/services/ble_messaging_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i18;

import 'package:bluetooth_low_energy/bluetooth_low_energy.dart' as _i2;
import 'package:logging/logging.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:pak_connect/core/interfaces/i_ble_state_manager_facade.dart'
    as _i10;
import 'package:pak_connect/core/models/ble_server_connection.dart' as _i7;
import 'package:pak_connect/core/models/connection_state.dart' as _i5;
import 'package:pak_connect/core/models/protocol_message.dart' as _i12;
import 'package:pak_connect/core/models/spy_mode_info.dart' as _i13;
import 'package:pak_connect/core/power/adaptive_power_manager.dart' as _i9;
import 'package:pak_connect/core/services/security_manager.dart' as _i16;
import 'package:pak_connect/data/models/ble_client_connection.dart' as _i6;
import 'package:pak_connect/data/repositories/contact_repository.dart' as _i17;
import 'package:pak_connect/data/services/ble_connection_manager.dart' as _i4;
import 'package:pak_connect/domain/entities/contact.dart' as _i15;
import 'package:pak_connect/domain/values/id_types.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCentralManager_0 extends _i1.SmartFake
    implements _i2.CentralManager {
  _FakeCentralManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeripheralManager_1 extends _i1.SmartFake
    implements _i2.PeripheralManager {
  _FakePeripheralManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLevel_2 extends _i1.SmartFake implements _i3.Level {
  _FakeLevel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BLEConnectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBLEConnectionManager extends _i1.Mock
    implements _i4.BLEConnectionManager {
  @override
  _i2.CentralManager get centralManager =>
      (super.noSuchMethod(
            Invocation.getter(#centralManager),
            returnValue: _FakeCentralManager_0(
              this,
              Invocation.getter(#centralManager),
            ),
            returnValueForMissingStub: _FakeCentralManager_0(
              this,
              Invocation.getter(#centralManager),
            ),
          )
          as _i2.CentralManager);

  @override
  _i2.PeripheralManager get peripheralManager =>
      (super.noSuchMethod(
            Invocation.getter(#peripheralManager),
            returnValue: _FakePeripheralManager_1(
              this,
              Invocation.getter(#peripheralManager),
            ),
            returnValueForMissingStub: _FakePeripheralManager_1(
              this,
              Invocation.getter(#peripheralManager),
            ),
          )
          as _i2.PeripheralManager);

  @override
  bool get hasBleConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasBleConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isReconnection =>
      (super.noSuchMethod(
            Invocation.getter(#isReconnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isMonitoring =>
      (super.noSuchMethod(
            Invocation.getter(#isMonitoring),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.ChatConnectionState get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i5.ChatConnectionState.disconnected,
            returnValueForMissingStub: _i5.ChatConnectionState.disconnected,
          )
          as _i5.ChatConnectionState);

  @override
  bool get isActivelyReconnecting =>
      (super.noSuchMethod(
            Invocation.getter(#isActivelyReconnecting),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isHealthChecking =>
      (super.noSuchMethod(
            Invocation.getter(#isHealthChecking),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get clientConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#clientConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get serverConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#serverConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get totalConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#totalConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get canAcceptClientConnection =>
      (super.noSuchMethod(
            Invocation.getter(#canAcceptClientConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canAcceptServerConnection =>
      (super.noSuchMethod(
            Invocation.getter(#canAcceptServerConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAdvertising =>
      (super.noSuchMethod(
            Invocation.getter(#isAdvertising),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i6.BLEClientConnection> get clientConnections =>
      (super.noSuchMethod(
            Invocation.getter(#clientConnections),
            returnValue: <_i6.BLEClientConnection>[],
            returnValueForMissingStub: <_i6.BLEClientConnection>[],
          )
          as List<_i6.BLEClientConnection>);

  @override
  List<_i7.BLEServerConnection> get serverConnections =>
      (super.noSuchMethod(
            Invocation.getter(#serverConnections),
            returnValue: <_i7.BLEServerConnection>[],
            returnValueForMissingStub: <_i7.BLEServerConnection>[],
          )
          as List<_i7.BLEServerConnection>);

  @override
  List<String> get connectedAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#connectedAddresses),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  int get activeConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get canAcceptMoreConnections =>
      (super.noSuchMethod(
            Invocation.getter(#canAcceptMoreConnections),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.Peripheral> get activeConnections =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnections),
            returnValue: <_i2.Peripheral>[],
            returnValueForMissingStub: <_i2.Peripheral>[],
          )
          as List<_i2.Peripheral>);

  @override
  int get maxClientConnections =>
      (super.noSuchMethod(
            Invocation.getter(#maxClientConnections),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  set onConnectionChanged(
    dynamic Function(_i2.Peripheral?)? _onConnectionChanged,
  ) => super.noSuchMethod(
    Invocation.setter(#onConnectionChanged, _onConnectionChanged),
    returnValueForMissingStub: null,
  );

  @override
  set onCharacteristicFound(
    dynamic Function(_i2.GATTCharacteristic?)? _onCharacteristicFound,
  ) => super.noSuchMethod(
    Invocation.setter(#onCharacteristicFound, _onCharacteristicFound),
    returnValueForMissingStub: null,
  );

  @override
  set onMtuDetected(dynamic Function(int?)? _onMtuDetected) =>
      super.noSuchMethod(
        Invocation.setter(#onMtuDetected, _onMtuDetected),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionComplete(dynamic Function()? _onConnectionComplete) =>
      super.noSuchMethod(
        Invocation.setter(#onConnectionComplete, _onConnectionComplete),
        returnValueForMissingStub: null,
      );

  @override
  set onMonitoringChanged(dynamic Function(bool)? _onMonitoringChanged) =>
      super.noSuchMethod(
        Invocation.setter(#onMonitoringChanged, _onMonitoringChanged),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionInfoChanged(
    dynamic Function(_i5.ConnectionInfo)? _onConnectionInfoChanged,
  ) => super.noSuchMethod(
    Invocation.setter(#onConnectionInfoChanged, _onConnectionInfoChanged),
    returnValueForMissingStub: null,
  );

  @override
  set onCentralDisconnected(dynamic Function(String)? _onCentralDisconnected) =>
      super.noSuchMethod(
        Invocation.setter(#onCentralDisconnected, _onCentralDisconnected),
        returnValueForMissingStub: null,
      );

  @override
  void setLocalHintProvider(_i8.Future<String?> Function()? provider) =>
      super.noSuchMethod(
        Invocation.method(#setLocalHintProvider, [provider]),
        returnValueForMissingStub: null,
      );

  @override
  void startConnectionMonitoring() => super.noSuchMethod(
    Invocation.method(#startConnectionMonitoring, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopConnectionMonitoring() => super.noSuchMethod(
    Invocation.method(#stopConnectionMonitoring, []),
    returnValueForMissingStub: null,
  );

  @override
  void setPairingInProgress(bool? inProgress) => super.noSuchMethod(
    Invocation.method(#setPairingInProgress, [inProgress]),
    returnValueForMissingStub: null,
  );

  @override
  void setHandshakeInProgress(bool? inProgress) => super.noSuchMethod(
    Invocation.method(#setHandshakeInProgress, [inProgress]),
    returnValueForMissingStub: null,
  );

  @override
  void startHealthChecks() => super.noSuchMethod(
    Invocation.method(#startHealthChecks, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> startMeshNetworking({
    _i8.Future<void> Function()? onStartAdvertising,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startMeshNetworking, [], {
              #onStartAdvertising: onStartAdvertising,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> stopMeshNetworking() =>
      (super.noSuchMethod(
            Invocation.method(#stopMeshNetworking, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void handleCentralConnected(_i2.Central? central) => super.noSuchMethod(
    Invocation.method(#handleCentralConnected, [central]),
    returnValueForMissingStub: null,
  );

  @override
  void handleCentralDisconnected(_i2.Central? central) => super.noSuchMethod(
    Invocation.method(#handleCentralDisconnected, [central]),
    returnValueForMissingStub: null,
  );

  @override
  void handleCharacteristicSubscribed(
    _i2.Central? central,
    _i2.GATTCharacteristic? characteristic,
  ) => super.noSuchMethod(
    Invocation.method(#handleCharacteristicSubscribed, [
      central,
      characteristic,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> handlePowerModeChange(_i9.PowerMode? newMode) =>
      (super.noSuchMethod(
            Invocation.method(#handlePowerModeChange, [newMode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void handleBluetoothStateChange(_i2.BluetoothLowEnergyState? state) =>
      super.noSuchMethod(
        Invocation.method(#handleBluetoothStateChange, [state]),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> connectToDevice(_i2.Peripheral? device, {int? rssi}) =>
      (super.noSuchMethod(
            Invocation.method(#connectToDevice, [device], {#rssi: rssi}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void setMessageOperationInProgress(bool? inProgress) => super.noSuchMethod(
    Invocation.method(#setMessageOperationInProgress, [inProgress]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i2.Peripheral?> scanForSpecificDevice({
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scanForSpecificDevice, [], {#timeout: timeout}),
            returnValue: _i8.Future<_i2.Peripheral?>.value(),
            returnValueForMissingStub: _i8.Future<_i2.Peripheral?>.value(),
          )
          as _i8.Future<_i2.Peripheral?>);

  @override
  _i8.Future<void> disconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectAll, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disconnectClient(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectClient, [address]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void triggerReconnection() => super.noSuchMethod(
    Invocation.method(#triggerReconnection, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearConnectionState({
    bool? keepMonitoring = false,
    String? contactId,
  }) => super.noSuchMethod(
    Invocation.method(#clearConnectionState, [], {
      #keepMonitoring: keepMonitoring,
      #contactId: contactId,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IBLEStateManagerFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBLEStateManagerFacade extends _i1.Mock
    implements _i10.IBLEStateManagerFacade {
  @override
  bool get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPeripheralMode =>
      (super.noSuchMethod(
            Invocation.getter(#isPeripheralMode),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasContactRequest =>
      (super.noSuchMethod(
            Invocation.getter(#hasContactRequest),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get theyHaveUsAsContact =>
      (super.noSuchMethod(
            Invocation.getter(#theyHaveUsAsContact),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<bool> get weHaveThemAsContact =>
      (super.noSuchMethod(
            Invocation.getter(#weHaveThemAsContact),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  bool get isPaired =>
      (super.noSuchMethod(
            Invocation.getter(#isPaired),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set onDeviceDiscovered(void Function(dynamic, int?)? _onDeviceDiscovered) =>
      super.noSuchMethod(
        Invocation.setter(#onDeviceDiscovered, _onDeviceDiscovered),
        returnValueForMissingStub: null,
      );

  @override
  set onMessageSent(void Function(String, bool)? _onMessageSent) =>
      super.noSuchMethod(
        Invocation.setter(#onMessageSent, _onMessageSent),
        returnValueForMissingStub: null,
      );

  @override
  set onMessageSentIds(
    void Function(_i11.MessageId, bool)? _onMessageSentIds,
  ) => super.noSuchMethod(
    Invocation.setter(#onMessageSentIds, _onMessageSentIds),
    returnValueForMissingStub: null,
  );

  @override
  set onNameChanged(void Function(String?)? _onNameChanged) =>
      super.noSuchMethod(
        Invocation.setter(#onNameChanged, _onNameChanged),
        returnValueForMissingStub: null,
      );

  @override
  set onMyUsernameChanged(void Function(String)? _onMyUsernameChanged) =>
      super.noSuchMethod(
        Invocation.setter(#onMyUsernameChanged, _onMyUsernameChanged),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingCode(void Function(String)? _onSendPairingCode) =>
      super.noSuchMethod(
        Invocation.setter(#onSendPairingCode, _onSendPairingCode),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingVerification(
    void Function(String)? _onSendPairingVerification,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingVerification, _onSendPairingVerification),
    returnValueForMissingStub: null,
  );

  @override
  set onContactRequestReceived(
    void Function(String, String)? _onContactRequestReceived,
  ) => super.noSuchMethod(
    Invocation.setter(#onContactRequestReceived, _onContactRequestReceived),
    returnValueForMissingStub: null,
  );

  @override
  set onContactRequestCompleted(
    void Function(bool)? _onContactRequestCompleted,
  ) => super.noSuchMethod(
    Invocation.setter(#onContactRequestCompleted, _onContactRequestCompleted),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactRequest(
    void Function(String, String)? _onSendContactRequest,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendContactRequest, _onSendContactRequest),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactAccept(
    void Function(String, String)? _onSendContactAccept,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendContactAccept, _onSendContactAccept),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactReject(void Function()? _onSendContactReject) =>
      super.noSuchMethod(
        Invocation.setter(#onSendContactReject, _onSendContactReject),
        returnValueForMissingStub: null,
      );

  @override
  set onSendContactStatus(
    void Function(_i12.ProtocolMessage)? _onSendContactStatus,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendContactStatus, _onSendContactStatus),
    returnValueForMissingStub: null,
  );

  @override
  set onAsymmetricContactDetected(
    void Function(String, String)? _onAsymmetricContactDetected,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onAsymmetricContactDetected,
      _onAsymmetricContactDetected,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onMutualConsentRequired(
    void Function(String, String)? _onMutualConsentRequired,
  ) => super.noSuchMethod(
    Invocation.setter(#onMutualConsentRequired, _onMutualConsentRequired),
    returnValueForMissingStub: null,
  );

  @override
  set onSpyModeDetected(void Function(_i13.SpyModeInfo)? _onSpyModeDetected) =>
      super.noSuchMethod(
        Invocation.setter(#onSpyModeDetected, _onSpyModeDetected),
        returnValueForMissingStub: null,
      );

  @override
  set onIdentityRevealed(void Function(String)? _onIdentityRevealed) =>
      super.noSuchMethod(
        Invocation.setter(#onIdentityRevealed, _onIdentityRevealed),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingRequest(
    void Function(_i12.ProtocolMessage)? _onSendPairingRequest,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingRequest, _onSendPairingRequest),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPairingAccept(
    void Function(_i12.ProtocolMessage)? _onSendPairingAccept,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingAccept, _onSendPairingAccept),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPairingCancel(
    void Function(_i12.ProtocolMessage)? _onSendPairingCancel,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingCancel, _onSendPairingCancel),
    returnValueForMissingStub: null,
  );

  @override
  set onPairingCancelled(void Function()? _onPairingCancelled) =>
      super.noSuchMethod(
        Invocation.setter(#onPairingCancelled, _onPairingCancelled),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPersistentKeyExchange(
    void Function(_i12.ProtocolMessage)? _onSendPersistentKeyExchange,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onSendPersistentKeyExchange,
      _onSendPersistentKeyExchange,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadUserName() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserName, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> getMyPersistentId() =>
      (super.noSuchMethod(
            Invocation.method(#getMyPersistentId, []),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#getMyPersistentId, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#getMyPersistentId, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> setMyUserName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setMyUserName, [name]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setMyUserNameWithCallbacks(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setMyUserNameWithCallbacks, [name]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void clearOtherUserName() => super.noSuchMethod(
    Invocation.method(#clearOtherUserName, []),
    returnValueForMissingStub: null,
  );

  @override
  void setOtherUserName(String? name) => super.noSuchMethod(
    Invocation.method(#setOtherUserName, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void setOtherDeviceIdentity(String? deviceId, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#setOtherDeviceIdentity, [deviceId, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  void setTheirEphemeralId(String? ephemeralId, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#setTheirEphemeralId, [ephemeralId, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  String getIdType() =>
      (super.noSuchMethod(
            Invocation.method(#getIdType, []),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#getIdType, []),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#getIdType, []),
            ),
          )
          as String);

  @override
  String? getPersistentKeyFromEphemeral(String? ephemeralId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersistentKeyFromEphemeral, [ephemeralId]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i8.Future<void> saveContact(String? publicKey, String? userName) =>
      (super.noSuchMethod(
            Invocation.method(#saveContact, [publicKey, userName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i15.Contact?> getContact(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContact, [publicKey]),
            returnValue: _i8.Future<_i15.Contact?>.value(),
            returnValueForMissingStub: _i8.Future<_i15.Contact?>.value(),
          )
          as _i8.Future<_i15.Contact?>);

  @override
  _i8.Future<Map<String, _i15.Contact>> getAllContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContacts, []),
            returnValue: _i8.Future<Map<String, _i15.Contact>>.value(
              <String, _i15.Contact>{},
            ),
            returnValueForMissingStub:
                _i8.Future<Map<String, _i15.Contact>>.value(
                  <String, _i15.Contact>{},
                ),
          )
          as _i8.Future<Map<String, _i15.Contact>>);

  @override
  _i8.Future<String?> getContactName(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactName, [publicKey]),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> markContactVerified(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#markContactVerified, [publicKey]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i15.TrustStatus> getContactTrustStatus(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactTrustStatus, [publicKey]),
            returnValue: _i8.Future<_i15.TrustStatus>.value(
              _i15.TrustStatus.newContact,
            ),
            returnValueForMissingStub: _i8.Future<_i15.TrustStatus>.value(
              _i15.TrustStatus.newContact,
            ),
          )
          as _i8.Future<_i15.TrustStatus>);

  @override
  _i8.Future<bool> hasContactKeyChanged(
    String? publicKey,
    String? currentDisplayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasContactKeyChanged, [
              publicKey,
              currentDisplayName,
            ]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> sendPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#sendPairingRequest, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> handlePairingRequest(_i12.ProtocolMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#handlePairingRequest, [message]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> acceptPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#acceptPairingRequest, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void rejectPairingRequest() => super.noSuchMethod(
    Invocation.method(#rejectPairingRequest, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> handlePairingAccept(_i12.ProtocolMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#handlePairingAccept, [message]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void handlePairingCancel(_i12.ProtocolMessage? message) => super.noSuchMethod(
    Invocation.method(#handlePairingCancel, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void cancelPairing({String? reason}) => super.noSuchMethod(
    Invocation.method(#cancelPairing, [], {#reason: reason}),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> handleContactRequest(
    String? publicKey,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleContactRequest, [publicKey, displayName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> acceptContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#acceptContactRequest, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void rejectContactRequest() => super.noSuchMethod(
    Invocation.method(#rejectContactRequest, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> sendContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#sendContactRequest, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> handleContactAccept(
    String? publicKey,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleContactAccept, [publicKey, displayName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void handleContactReject() => super.noSuchMethod(
    Invocation.method(#handleContactReject, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> initiateContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#initiateContactRequest, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> ensureContactMaximumSecurity(String? contactPublicKey) =>
      (super.noSuchMethod(
            Invocation.method(#ensureContactMaximumSecurity, [
              contactPublicKey,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> checkExistingPairing(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#checkExistingPairing, [publicKey]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> checkForQRIntroduction(
    String? otherPublicKey,
    String? otherName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkForQRIntroduction, [
              otherPublicKey,
              otherName,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> requestSecurityLevelSync() =>
      (super.noSuchMethod(
            Invocation.method(#requestSecurityLevelSync, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> handleSecurityLevelSync(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
            Invocation.method(#handleSecurityLevelSync, [payload]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> confirmSecurityUpgrade(
    String? publicKey,
    _i16.SecurityLevel? newLevel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSecurityUpgrade, [publicKey, newLevel]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> resetContactSecurity(String? publicKey, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#resetContactSecurity, [publicKey, reason]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> handleContactStatus(
    bool? theyHaveUsAsContact,
    String? theirPublicKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleContactStatus, [
              theyHaveUsAsContact,
              theirPublicKey,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> requestContactStatusExchange() =>
      (super.noSuchMethod(
            Invocation.method(#requestContactStatusExchange, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void preserveContactRelationship({
    String? otherPublicKey,
    String? otherName,
    bool? theyHaveUs,
    bool? weHaveThem,
  }) => super.noSuchMethod(
    Invocation.method(#preserveContactRelationship, [], {
      #otherPublicKey: otherPublicKey,
      #otherName: otherName,
      #theyHaveUs: theyHaveUs,
      #weHaveThem: weHaveThem,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i12.ProtocolMessage?> revealIdentityToFriend() =>
      (super.noSuchMethod(
            Invocation.method(#revealIdentityToFriend, []),
            returnValue: _i8.Future<_i12.ProtocolMessage?>.value(),
            returnValueForMissingStub:
                _i8.Future<_i12.ProtocolMessage?>.value(),
          )
          as _i8.Future<_i12.ProtocolMessage?>);

  @override
  void setPeripheralMode(bool? isPeripheral) => super.noSuchMethod(
    Invocation.method(#setPeripheralMode, [isPeripheral]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSessionState({bool? preservePersistentId = false}) =>
      super.noSuchMethod(
        Invocation.method(#clearSessionState, [], {
          #preservePersistentId: preservePersistentId,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> recoverIdentityFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#recoverIdentityFromStorage, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, String?>> getIdentityWithFallback() =>
      (super.noSuchMethod(
            Invocation.method(#getIdentityWithFallback, []),
            returnValue: _i8.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
            returnValueForMissingStub: _i8.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i8.Future<Map<String, String?>>);
}

/// A class which mocks [ContactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactRepository extends _i1.Mock implements _i17.ContactRepository {
  @override
  _i8.Future<void> saveContact(String? publicKey, String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#saveContact, [publicKey, displayName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i15.Contact?> getContact(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContact, [publicKey]),
            returnValue: _i8.Future<_i15.Contact?>.value(),
            returnValueForMissingStub: _i8.Future<_i15.Contact?>.value(),
          )
          as _i8.Future<_i15.Contact?>);

  @override
  _i8.Future<_i15.Contact?> getContactByUserId(_i11.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByUserId, [userId]),
            returnValue: _i8.Future<_i15.Contact?>.value(),
            returnValueForMissingStub: _i8.Future<_i15.Contact?>.value(),
          )
          as _i8.Future<_i15.Contact?>);

  @override
  _i8.Future<_i15.Contact?> getContactByPersistentKey(
    String? persistentPublicKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByPersistentKey, [
              persistentPublicKey,
            ]),
            returnValue: _i8.Future<_i15.Contact?>.value(),
            returnValueForMissingStub: _i8.Future<_i15.Contact?>.value(),
          )
          as _i8.Future<_i15.Contact?>);

  @override
  _i8.Future<_i15.Contact?> getContactByPersistentUserId(
    _i11.UserId? persistentUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByPersistentUserId, [
              persistentUserId,
            ]),
            returnValue: _i8.Future<_i15.Contact?>.value(),
            returnValueForMissingStub: _i8.Future<_i15.Contact?>.value(),
          )
          as _i8.Future<_i15.Contact?>);

  @override
  _i8.Future<_i15.Contact?> getContactByCurrentEphemeralId(
    String? ephemeralId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByCurrentEphemeralId, [ephemeralId]),
            returnValue: _i8.Future<_i15.Contact?>.value(),
            returnValueForMissingStub: _i8.Future<_i15.Contact?>.value(),
          )
          as _i8.Future<_i15.Contact?>);

  @override
  _i8.Future<_i15.Contact?> getContactByAnyId(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByAnyId, [identifier]),
            returnValue: _i8.Future<_i15.Contact?>.value(),
            returnValueForMissingStub: _i8.Future<_i15.Contact?>.value(),
          )
          as _i8.Future<_i15.Contact?>);

  @override
  _i8.Future<Map<String, _i15.Contact>> getAllContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContacts, []),
            returnValue: _i8.Future<Map<String, _i15.Contact>>.value(
              <String, _i15.Contact>{},
            ),
            returnValueForMissingStub:
                _i8.Future<Map<String, _i15.Contact>>.value(
                  <String, _i15.Contact>{},
                ),
          )
          as _i8.Future<Map<String, _i15.Contact>>);

  @override
  _i8.Future<void> markContactVerified(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#markContactVerified, [publicKey]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateNoiseSession({
    required String? publicKey,
    required String? noisePublicKey,
    required String? sessionState,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoiseSession, [], {
              #publicKey: publicKey,
              #noisePublicKey: noisePublicKey,
              #sessionState: sessionState,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> cacheSharedSecret(String? publicKey, String? sharedSecret) =>
      (super.noSuchMethod(
            Invocation.method(#cacheSharedSecret, [publicKey, sharedSecret]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getCachedSharedSecret(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSharedSecret, [publicKey]),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> cacheSharedSeedBytes(
    String? publicKey,
    _i18.Uint8List? seedBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheSharedSeedBytes, [publicKey, seedBytes]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i18.Uint8List?> getCachedSharedSeedBytes(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSharedSeedBytes, [publicKey]),
            returnValue: _i8.Future<_i18.Uint8List?>.value(),
            returnValueForMissingStub: _i8.Future<_i18.Uint8List?>.value(),
          )
          as _i8.Future<_i18.Uint8List?>);

  @override
  _i8.Future<String?> getContactName(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactName, [publicKey]),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> updateContactSecurityLevel(
    String? publicKey,
    _i16.SecurityLevel? newLevel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateContactSecurityLevel, [
              publicKey,
              newLevel,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateContactEphemeralId(
    String? publicKey,
    String? newEphemeralId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateContactEphemeralId, [
              publicKey,
              newEphemeralId,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i16.SecurityLevel> getContactSecurityLevel(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactSecurityLevel, [publicKey]),
            returnValue: _i8.Future<_i16.SecurityLevel>.value(
              _i16.SecurityLevel.low,
            ),
            returnValueForMissingStub: _i8.Future<_i16.SecurityLevel>.value(
              _i16.SecurityLevel.low,
            ),
          )
          as _i8.Future<_i16.SecurityLevel>);

  @override
  _i8.Future<void> downgradeSecurityForDeletedContact(
    String? publicKey,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downgradeSecurityForDeletedContact, [
              publicKey,
              reason,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> upgradeContactSecurity(
    String? publicKey,
    _i16.SecurityLevel? newLevel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeContactSecurity, [publicKey, newLevel]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> resetContactSecurity(String? publicKey, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#resetContactSecurity, [publicKey, reason]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> clearCachedSecrets(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedSecrets, [publicKey]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveContactWithSecurity(
    String? publicKey,
    String? displayName,
    _i16.SecurityLevel? securityLevel, {
    String? currentEphemeralId,
    String? persistentPublicKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveContactWithSecurity,
              [publicKey, displayName, securityLevel],
              {
                #currentEphemeralId: currentEphemeralId,
                #persistentPublicKey: persistentPublicKey,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> deleteContact(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#deleteContact, [publicKey]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<int> getContactCount() =>
      (super.noSuchMethod(
            Invocation.method(#getContactCount, []),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> getVerifiedContactCount() =>
      (super.noSuchMethod(
            Invocation.method(#getVerifiedContactCount, []),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<Map<_i16.SecurityLevel, int>> getContactsBySecurityLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getContactsBySecurityLevel, []),
            returnValue: _i8.Future<Map<_i16.SecurityLevel, int>>.value(
              <_i16.SecurityLevel, int>{},
            ),
            returnValueForMissingStub:
                _i8.Future<Map<_i16.SecurityLevel, int>>.value(
                  <_i16.SecurityLevel, int>{},
                ),
          )
          as _i8.Future<Map<_i16.SecurityLevel, int>>);

  @override
  _i8.Future<int> getRecentlyActiveContactCount() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyActiveContactCount, []),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> markContactFavorite(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#markContactFavorite, [publicKey]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> unmarkContactFavorite(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#unmarkContactFavorite, [publicKey]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> toggleContactFavorite(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#toggleContactFavorite, [publicKey]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i15.Contact>> getFavoriteContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteContacts, []),
            returnValue: _i8.Future<List<_i15.Contact>>.value(<_i15.Contact>[]),
            returnValueForMissingStub: _i8.Future<List<_i15.Contact>>.value(
              <_i15.Contact>[],
            ),
          )
          as _i8.Future<List<_i15.Contact>>);

  @override
  _i8.Future<int> getFavoriteContactCount() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteContactCount, []),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<bool> isContactFavorite(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#isContactFavorite, [publicKey]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [CentralManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCentralManager extends _i1.Mock implements _i2.CentralManager {
  @override
  _i8.Stream<_i2.DiscoveredEventArgs> get discovered =>
      (super.noSuchMethod(
            Invocation.getter(#discovered),
            returnValue: _i8.Stream<_i2.DiscoveredEventArgs>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.DiscoveredEventArgs>.empty(),
          )
          as _i8.Stream<_i2.DiscoveredEventArgs>);

  @override
  _i8.Stream<_i2.PeripheralConnectionStateChangedEventArgs>
  get connectionStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStateChanged),
            returnValue:
                _i8.Stream<
                  _i2.PeripheralConnectionStateChangedEventArgs
                >.empty(),
            returnValueForMissingStub:
                _i8.Stream<
                  _i2.PeripheralConnectionStateChangedEventArgs
                >.empty(),
          )
          as _i8.Stream<_i2.PeripheralConnectionStateChangedEventArgs>);

  @override
  _i8.Stream<_i2.PeripheralMTUChangedEventArgs> get mtuChanged =>
      (super.noSuchMethod(
            Invocation.getter(#mtuChanged),
            returnValue: _i8.Stream<_i2.PeripheralMTUChangedEventArgs>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.PeripheralMTUChangedEventArgs>.empty(),
          )
          as _i8.Stream<_i2.PeripheralMTUChangedEventArgs>);

  @override
  _i8.Stream<_i2.GATTCharacteristicNotifiedEventArgs>
  get characteristicNotified =>
      (super.noSuchMethod(
            Invocation.getter(#characteristicNotified),
            returnValue:
                _i8.Stream<_i2.GATTCharacteristicNotifiedEventArgs>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.GATTCharacteristicNotifiedEventArgs>.empty(),
          )
          as _i8.Stream<_i2.GATTCharacteristicNotifiedEventArgs>);

  @override
  _i2.BluetoothLowEnergyState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i2.BluetoothLowEnergyState.unknown,
            returnValueForMissingStub: _i2.BluetoothLowEnergyState.unknown,
          )
          as _i2.BluetoothLowEnergyState);

  @override
  _i8.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs> get stateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#stateChanged),
            returnValue:
                _i8.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs>.empty(),
          )
          as _i8.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs>);

  @override
  _i3.Level get logLevel =>
      (super.noSuchMethod(
            Invocation.getter(#logLevel),
            returnValue: _FakeLevel_2(this, Invocation.getter(#logLevel)),
            returnValueForMissingStub: _FakeLevel_2(
              this,
              Invocation.getter(#logLevel),
            ),
          )
          as _i3.Level);

  @override
  set logLevel(_i3.Level? value) => super.noSuchMethod(
    Invocation.setter(#logLevel, value),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> startDiscovery({List<_i2.UUID>? serviceUUIDs}) =>
      (super.noSuchMethod(
            Invocation.method(#startDiscovery, [], {
              #serviceUUIDs: serviceUUIDs,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.Peripheral>> retrieveConnectedPeripherals() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveConnectedPeripherals, []),
            returnValue: _i8.Future<List<_i2.Peripheral>>.value(
              <_i2.Peripheral>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i2.Peripheral>>.value(
              <_i2.Peripheral>[],
            ),
          )
          as _i8.Future<List<_i2.Peripheral>>);

  @override
  _i8.Future<void> connect(_i2.Peripheral? peripheral) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [peripheral]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disconnect(_i2.Peripheral? peripheral) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [peripheral]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> requestMTU(_i2.Peripheral? peripheral, {required int? mtu}) =>
      (super.noSuchMethod(
            Invocation.method(#requestMTU, [peripheral], {#mtu: mtu}),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> getMaximumWriteLength(
    _i2.Peripheral? peripheral, {
    required _i2.GATTCharacteristicWriteType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMaximumWriteLength,
              [peripheral],
              {#type: type},
            ),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> readRSSI(_i2.Peripheral? peripheral) =>
      (super.noSuchMethod(
            Invocation.method(#readRSSI, [peripheral]),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i2.GATTService>> discoverGATT(_i2.Peripheral? peripheral) =>
      (super.noSuchMethod(
            Invocation.method(#discoverGATT, [peripheral]),
            returnValue: _i8.Future<List<_i2.GATTService>>.value(
              <_i2.GATTService>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i2.GATTService>>.value(
              <_i2.GATTService>[],
            ),
          )
          as _i8.Future<List<_i2.GATTService>>);

  @override
  _i8.Future<_i18.Uint8List> readCharacteristic(
    _i2.Peripheral? peripheral,
    _i2.GATTCharacteristic? characteristic,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readCharacteristic, [
              peripheral,
              characteristic,
            ]),
            returnValue: _i8.Future<_i18.Uint8List>.value(_i18.Uint8List(0)),
            returnValueForMissingStub: _i8.Future<_i18.Uint8List>.value(
              _i18.Uint8List(0),
            ),
          )
          as _i8.Future<_i18.Uint8List>);

  @override
  _i8.Future<void> writeCharacteristic(
    _i2.Peripheral? peripheral,
    _i2.GATTCharacteristic? characteristic, {
    required _i18.Uint8List? value,
    required _i2.GATTCharacteristicWriteType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeCharacteristic,
              [peripheral, characteristic],
              {#value: value, #type: type},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setCharacteristicNotifyState(
    _i2.Peripheral? peripheral,
    _i2.GATTCharacteristic? characteristic, {
    required bool? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setCharacteristicNotifyState,
              [peripheral, characteristic],
              {#state: state},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i18.Uint8List> readDescriptor(
    _i2.Peripheral? peripheral,
    _i2.GATTDescriptor? descriptor,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptor, [peripheral, descriptor]),
            returnValue: _i8.Future<_i18.Uint8List>.value(_i18.Uint8List(0)),
            returnValueForMissingStub: _i8.Future<_i18.Uint8List>.value(
              _i18.Uint8List(0),
            ),
          )
          as _i8.Future<_i18.Uint8List>);

  @override
  _i8.Future<void> writeDescriptor(
    _i2.Peripheral? peripheral,
    _i2.GATTDescriptor? descriptor, {
    required _i18.Uint8List? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeDescriptor,
              [peripheral, descriptor],
              {#value: value},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> authorize() =>
      (super.noSuchMethod(
            Invocation.method(#authorize, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> showAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#showAppSettings, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [PeripheralManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeripheralManager extends _i1.Mock implements _i2.PeripheralManager {
  @override
  _i8.Stream<_i2.CentralConnectionStateChangedEventArgs>
  get connectionStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStateChanged),
            returnValue:
                _i8.Stream<_i2.CentralConnectionStateChangedEventArgs>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.CentralConnectionStateChangedEventArgs>.empty(),
          )
          as _i8.Stream<_i2.CentralConnectionStateChangedEventArgs>);

  @override
  _i8.Stream<_i2.CentralMTUChangedEventArgs> get mtuChanged =>
      (super.noSuchMethod(
            Invocation.getter(#mtuChanged),
            returnValue: _i8.Stream<_i2.CentralMTUChangedEventArgs>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.CentralMTUChangedEventArgs>.empty(),
          )
          as _i8.Stream<_i2.CentralMTUChangedEventArgs>);

  @override
  _i8.Stream<_i2.GATTCharacteristicReadRequestedEventArgs>
  get characteristicReadRequested =>
      (super.noSuchMethod(
            Invocation.getter(#characteristicReadRequested),
            returnValue:
                _i8.Stream<
                  _i2.GATTCharacteristicReadRequestedEventArgs
                >.empty(),
            returnValueForMissingStub:
                _i8.Stream<
                  _i2.GATTCharacteristicReadRequestedEventArgs
                >.empty(),
          )
          as _i8.Stream<_i2.GATTCharacteristicReadRequestedEventArgs>);

  @override
  _i8.Stream<_i2.GATTCharacteristicWriteRequestedEventArgs>
  get characteristicWriteRequested =>
      (super.noSuchMethod(
            Invocation.getter(#characteristicWriteRequested),
            returnValue:
                _i8.Stream<
                  _i2.GATTCharacteristicWriteRequestedEventArgs
                >.empty(),
            returnValueForMissingStub:
                _i8.Stream<
                  _i2.GATTCharacteristicWriteRequestedEventArgs
                >.empty(),
          )
          as _i8.Stream<_i2.GATTCharacteristicWriteRequestedEventArgs>);

  @override
  _i8.Stream<_i2.GATTCharacteristicNotifyStateChangedEventArgs>
  get characteristicNotifyStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#characteristicNotifyStateChanged),
            returnValue:
                _i8.Stream<
                  _i2.GATTCharacteristicNotifyStateChangedEventArgs
                >.empty(),
            returnValueForMissingStub:
                _i8.Stream<
                  _i2.GATTCharacteristicNotifyStateChangedEventArgs
                >.empty(),
          )
          as _i8.Stream<_i2.GATTCharacteristicNotifyStateChangedEventArgs>);

  @override
  _i8.Stream<_i2.GATTDescriptorReadRequestedEventArgs>
  get descriptorReadRequested =>
      (super.noSuchMethod(
            Invocation.getter(#descriptorReadRequested),
            returnValue:
                _i8.Stream<_i2.GATTDescriptorReadRequestedEventArgs>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.GATTDescriptorReadRequestedEventArgs>.empty(),
          )
          as _i8.Stream<_i2.GATTDescriptorReadRequestedEventArgs>);

  @override
  _i8.Stream<_i2.GATTDescriptorWriteRequestedEventArgs>
  get descriptorWriteRequested =>
      (super.noSuchMethod(
            Invocation.getter(#descriptorWriteRequested),
            returnValue:
                _i8.Stream<_i2.GATTDescriptorWriteRequestedEventArgs>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.GATTDescriptorWriteRequestedEventArgs>.empty(),
          )
          as _i8.Stream<_i2.GATTDescriptorWriteRequestedEventArgs>);

  @override
  _i2.BluetoothLowEnergyState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i2.BluetoothLowEnergyState.unknown,
            returnValueForMissingStub: _i2.BluetoothLowEnergyState.unknown,
          )
          as _i2.BluetoothLowEnergyState);

  @override
  _i8.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs> get stateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#stateChanged),
            returnValue:
                _i8.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs>.empty(),
          )
          as _i8.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs>);

  @override
  _i3.Level get logLevel =>
      (super.noSuchMethod(
            Invocation.getter(#logLevel),
            returnValue: _FakeLevel_2(this, Invocation.getter(#logLevel)),
            returnValueForMissingStub: _FakeLevel_2(
              this,
              Invocation.getter(#logLevel),
            ),
          )
          as _i3.Level);

  @override
  set logLevel(_i3.Level? value) => super.noSuchMethod(
    Invocation.setter(#logLevel, value),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> addService(_i2.GATTService? service) =>
      (super.noSuchMethod(
            Invocation.method(#addService, [service]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeService(_i2.GATTService? service) =>
      (super.noSuchMethod(
            Invocation.method(#removeService, [service]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeAllServices() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllServices, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> startAdvertising(_i2.Advertisement? advertisement) =>
      (super.noSuchMethod(
            Invocation.method(#startAdvertising, [advertisement]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getMaximumNotifyLength(_i2.Central? central) =>
      (super.noSuchMethod(
            Invocation.method(#getMaximumNotifyLength, [central]),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> respondReadRequestWithValue(
    _i2.GATTReadRequest? request, {
    required _i18.Uint8List? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #respondReadRequestWithValue,
              [request],
              {#value: value},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> respondReadRequestWithError(
    _i2.GATTReadRequest? request, {
    required _i2.GATTError? error,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #respondReadRequestWithError,
              [request],
              {#error: error},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> respondWriteRequest(_i2.GATTWriteRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#respondWriteRequest, [request]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> respondWriteRequestWithError(
    _i2.GATTWriteRequest? request, {
    required _i2.GATTError? error,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #respondWriteRequestWithError,
              [request],
              {#error: error},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> notifyCharacteristic(
    _i2.Central? central,
    _i2.GATTCharacteristic? characteristic, {
    required _i18.Uint8List? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #notifyCharacteristic,
              [central, characteristic],
              {#value: value},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> authorize() =>
      (super.noSuchMethod(
            Invocation.method(#authorize, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> showAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#showAppSettings, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
