// Mocks generated by Mockito 5.4.6 from annotations
// in pak_connect/test/services/ble_connection_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i16;

import 'package:bluetooth_low_energy/bluetooth_low_energy.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:pak_connect/core/bluetooth/bluetooth_state_monitor.dart'
    as _i17;
import 'package:pak_connect/core/interfaces/i_ble_state_manager_facade.dart'
    as _i3;
import 'package:pak_connect/core/models/ble_server_connection.dart' as _i12;
import 'package:pak_connect/core/models/connection_state.dart' as _i13;
import 'package:pak_connect/core/models/protocol_message.dart' as _i6;
import 'package:pak_connect/core/models/spy_mode_info.dart' as _i7;
import 'package:pak_connect/core/power/adaptive_power_manager.dart' as _i15;
import 'package:pak_connect/core/services/security_manager.dart' as _i10;
import 'package:pak_connect/data/models/ble_client_connection.dart' as _i14;
import 'package:pak_connect/data/services/ble_connection_manager.dart' as _i11;
import 'package:pak_connect/domain/entities/contact.dart' as _i9;
import 'package:pak_connect/domain/values/id_types.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCentralManager_0 extends _i1.SmartFake
    implements _i2.CentralManager {
  _FakeCentralManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeripheralManager_1 extends _i1.SmartFake
    implements _i2.PeripheralManager {
  _FakePeripheralManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeripheral_2 extends _i1.SmartFake implements _i2.Peripheral {
  _FakePeripheral_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IBLEStateManagerFacade].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBLEStateManagerFacade extends _i1.Mock
    implements _i3.IBLEStateManagerFacade {
  @override
  bool get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPeripheralMode =>
      (super.noSuchMethod(
            Invocation.getter(#isPeripheralMode),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasContactRequest =>
      (super.noSuchMethod(
            Invocation.getter(#hasContactRequest),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get theyHaveUsAsContact =>
      (super.noSuchMethod(
            Invocation.getter(#theyHaveUsAsContact),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<bool> get weHaveThemAsContact =>
      (super.noSuchMethod(
            Invocation.getter(#weHaveThemAsContact),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  bool get isPaired =>
      (super.noSuchMethod(
            Invocation.getter(#isPaired),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set onDeviceDiscovered(void Function(dynamic, int?)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onDeviceDiscovered, value),
        returnValueForMissingStub: null,
      );

  @override
  set onMessageSent(void Function(String, bool)? value) => super.noSuchMethod(
    Invocation.setter(#onMessageSent, value),
    returnValueForMissingStub: null,
  );

  @override
  set onMessageSentIds(void Function(_i5.MessageId, bool)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onMessageSentIds, value),
        returnValueForMissingStub: null,
      );

  @override
  set onNameChanged(void Function(String?)? value) => super.noSuchMethod(
    Invocation.setter(#onNameChanged, value),
    returnValueForMissingStub: null,
  );

  @override
  set onMyUsernameChanged(void Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onMyUsernameChanged, value),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPairingCode(void Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onSendPairingCode, value),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPairingVerification(void Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSendPairingVerification, value),
        returnValueForMissingStub: null,
      );

  @override
  set onContactRequestReceived(void Function(String, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onContactRequestReceived, value),
        returnValueForMissingStub: null,
      );

  @override
  set onContactRequestCompleted(void Function(bool)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onContactRequestCompleted, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSendContactRequest(void Function(String, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSendContactRequest, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSendContactAccept(void Function(String, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSendContactAccept, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSendContactReject(void Function()? value) => super.noSuchMethod(
    Invocation.setter(#onSendContactReject, value),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactStatus(void Function(_i6.ProtocolMessage)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSendContactStatus, value),
        returnValueForMissingStub: null,
      );

  @override
  set onAsymmetricContactDetected(void Function(String, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onAsymmetricContactDetected, value),
        returnValueForMissingStub: null,
      );

  @override
  set onMutualConsentRequired(void Function(String, String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onMutualConsentRequired, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSpyModeDetected(void Function(_i7.SpyModeInfo)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSpyModeDetected, value),
        returnValueForMissingStub: null,
      );

  @override
  set onIdentityRevealed(void Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onIdentityRevealed, value),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPairingRequest(void Function(_i6.ProtocolMessage)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSendPairingRequest, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingAccept(void Function(_i6.ProtocolMessage)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSendPairingAccept, value),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingCancel(void Function(_i6.ProtocolMessage)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSendPairingCancel, value),
        returnValueForMissingStub: null,
      );

  @override
  set onPairingCancelled(void Function()? value) => super.noSuchMethod(
    Invocation.setter(#onPairingCancelled, value),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPersistentKeyExchange(void Function(_i6.ProtocolMessage)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onSendPersistentKeyExchange, value),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadUserName() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserName, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getMyPersistentId() =>
      (super.noSuchMethod(
            Invocation.method(#getMyPersistentId, []),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getMyPersistentId, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getMyPersistentId, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> setMyUserName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setMyUserName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setMyUserNameWithCallbacks(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setMyUserNameWithCallbacks, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearOtherUserName() => super.noSuchMethod(
    Invocation.method(#clearOtherUserName, []),
    returnValueForMissingStub: null,
  );

  @override
  void setOtherUserName(String? name) => super.noSuchMethod(
    Invocation.method(#setOtherUserName, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void setOtherDeviceIdentity(String? deviceId, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#setOtherDeviceIdentity, [deviceId, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  void setTheirEphemeralId(String? ephemeralId, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#setTheirEphemeralId, [ephemeralId, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  String getIdType() =>
      (super.noSuchMethod(
            Invocation.method(#getIdType, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getIdType, []),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#getIdType, []),
            ),
          )
          as String);

  @override
  String? getPersistentKeyFromEphemeral(String? ephemeralId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersistentKeyFromEphemeral, [ephemeralId]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i4.Future<void> saveContact(String? publicKey, String? userName) =>
      (super.noSuchMethod(
            Invocation.method(#saveContact, [publicKey, userName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i9.Contact?> getContact(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContact, [publicKey]),
            returnValue: _i4.Future<_i9.Contact?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.Contact?>.value(),
          )
          as _i4.Future<_i9.Contact?>);

  @override
  _i4.Future<Map<String, _i9.Contact>> getAllContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContacts, []),
            returnValue: _i4.Future<Map<String, _i9.Contact>>.value(
              <String, _i9.Contact>{},
            ),
            returnValueForMissingStub:
                _i4.Future<Map<String, _i9.Contact>>.value(
                  <String, _i9.Contact>{},
                ),
          )
          as _i4.Future<Map<String, _i9.Contact>>);

  @override
  _i4.Future<String?> getContactName(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactName, [publicKey]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> markContactVerified(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#markContactVerified, [publicKey]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i9.TrustStatus> getContactTrustStatus(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactTrustStatus, [publicKey]),
            returnValue: _i4.Future<_i9.TrustStatus>.value(
              _i9.TrustStatus.newContact,
            ),
            returnValueForMissingStub: _i4.Future<_i9.TrustStatus>.value(
              _i9.TrustStatus.newContact,
            ),
          )
          as _i4.Future<_i9.TrustStatus>);

  @override
  _i4.Future<bool> hasContactKeyChanged(
    String? publicKey,
    String? currentDisplayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasContactKeyChanged, [
              publicKey,
              currentDisplayName,
            ]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> sendPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#sendPairingRequest, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> handlePairingRequest(_i6.ProtocolMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#handlePairingRequest, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> acceptPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#acceptPairingRequest, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void rejectPairingRequest() => super.noSuchMethod(
    Invocation.method(#rejectPairingRequest, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> handlePairingAccept(_i6.ProtocolMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#handlePairingAccept, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void handlePairingCancel(_i6.ProtocolMessage? message) => super.noSuchMethod(
    Invocation.method(#handlePairingCancel, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void cancelPairing({String? reason}) => super.noSuchMethod(
    Invocation.method(#cancelPairing, [], {#reason: reason}),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> handleContactRequest(
    String? publicKey,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleContactRequest, [publicKey, displayName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> acceptContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#acceptContactRequest, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void rejectContactRequest() => super.noSuchMethod(
    Invocation.method(#rejectContactRequest, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> sendContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#sendContactRequest, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> handleContactAccept(
    String? publicKey,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleContactAccept, [publicKey, displayName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void handleContactReject() => super.noSuchMethod(
    Invocation.method(#handleContactReject, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> initiateContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#initiateContactRequest, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> ensureContactMaximumSecurity(String? contactPublicKey) =>
      (super.noSuchMethod(
            Invocation.method(#ensureContactMaximumSecurity, [
              contactPublicKey,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> checkExistingPairing(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#checkExistingPairing, [publicKey]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> checkForQRIntroduction(
    String? otherPublicKey,
    String? otherName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkForQRIntroduction, [
              otherPublicKey,
              otherName,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> requestSecurityLevelSync() =>
      (super.noSuchMethod(
            Invocation.method(#requestSecurityLevelSync, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> handleSecurityLevelSync(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
            Invocation.method(#handleSecurityLevelSync, [payload]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> confirmSecurityUpgrade(
    String? publicKey,
    _i10.SecurityLevel? newLevel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSecurityUpgrade, [publicKey, newLevel]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> resetContactSecurity(String? publicKey, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#resetContactSecurity, [publicKey, reason]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> handleContactStatus(
    bool? theyHaveUsAsContact,
    String? theirPublicKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleContactStatus, [
              theyHaveUsAsContact,
              theirPublicKey,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> requestContactStatusExchange() =>
      (super.noSuchMethod(
            Invocation.method(#requestContactStatusExchange, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void preserveContactRelationship({
    String? otherPublicKey,
    String? otherName,
    bool? theyHaveUs,
    bool? weHaveThem,
  }) => super.noSuchMethod(
    Invocation.method(#preserveContactRelationship, [], {
      #otherPublicKey: otherPublicKey,
      #otherName: otherName,
      #theyHaveUs: theyHaveUs,
      #weHaveThem: weHaveThem,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i6.ProtocolMessage?> revealIdentityToFriend() =>
      (super.noSuchMethod(
            Invocation.method(#revealIdentityToFriend, []),
            returnValue: _i4.Future<_i6.ProtocolMessage?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.ProtocolMessage?>.value(),
          )
          as _i4.Future<_i6.ProtocolMessage?>);

  @override
  void setPeripheralMode(bool? isPeripheral) => super.noSuchMethod(
    Invocation.method(#setPeripheralMode, [isPeripheral]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSessionState({bool? preservePersistentId = false}) =>
      super.noSuchMethod(
        Invocation.method(#clearSessionState, [], {
          #preservePersistentId: preservePersistentId,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> recoverIdentityFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#recoverIdentityFromStorage, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String?>> getIdentityWithFallback() =>
      (super.noSuchMethod(
            Invocation.method(#getIdentityWithFallback, []),
            returnValue: _i4.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i4.Future<Map<String, String?>>);
}

/// A class which mocks [BLEConnectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBLEConnectionManager extends _i1.Mock
    implements _i11.BLEConnectionManager {
  @override
  _i2.CentralManager get centralManager =>
      (super.noSuchMethod(
            Invocation.getter(#centralManager),
            returnValue: _FakeCentralManager_0(
              this,
              Invocation.getter(#centralManager),
            ),
            returnValueForMissingStub: _FakeCentralManager_0(
              this,
              Invocation.getter(#centralManager),
            ),
          )
          as _i2.CentralManager);

  @override
  _i2.PeripheralManager get peripheralManager =>
      (super.noSuchMethod(
            Invocation.getter(#peripheralManager),
            returnValue: _FakePeripheralManager_1(
              this,
              Invocation.getter(#peripheralManager),
            ),
            returnValueForMissingStub: _FakePeripheralManager_1(
              this,
              Invocation.getter(#peripheralManager),
            ),
          )
          as _i2.PeripheralManager);

  @override
  _i4.Stream<List<_i12.BLEServerConnection>> get serverConnectionsStream =>
      (super.noSuchMethod(
            Invocation.getter(#serverConnectionsStream),
            returnValue: _i4.Stream<List<_i12.BLEServerConnection>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i12.BLEServerConnection>>.empty(),
          )
          as _i4.Stream<List<_i12.BLEServerConnection>>);

  @override
  bool get hasBleConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasBleConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isReconnection =>
      (super.noSuchMethod(
            Invocation.getter(#isReconnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isMonitoring =>
      (super.noSuchMethod(
            Invocation.getter(#isMonitoring),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i13.ChatConnectionState get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i13.ChatConnectionState.disconnected,
            returnValueForMissingStub: _i13.ChatConnectionState.disconnected,
          )
          as _i13.ChatConnectionState);

  @override
  bool get isActivelyReconnecting =>
      (super.noSuchMethod(
            Invocation.getter(#isActivelyReconnecting),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isHealthChecking =>
      (super.noSuchMethod(
            Invocation.getter(#isHealthChecking),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasCollisionResolutionInFlight =>
      (super.noSuchMethod(
            Invocation.getter(#hasCollisionResolutionInFlight),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isHandshakeInProgress =>
      (super.noSuchMethod(
            Invocation.getter(#isHandshakeInProgress),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get awaitingHandshake =>
      (super.noSuchMethod(
            Invocation.getter(#awaitingHandshake),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get clientConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#clientConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get serverConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#serverConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get totalConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#totalConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get canAcceptClientConnection =>
      (super.noSuchMethod(
            Invocation.getter(#canAcceptClientConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canAcceptServerConnection =>
      (super.noSuchMethod(
            Invocation.getter(#canAcceptServerConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAdvertising =>
      (super.noSuchMethod(
            Invocation.getter(#isAdvertising),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i14.BLEClientConnection> get clientConnections =>
      (super.noSuchMethod(
            Invocation.getter(#clientConnections),
            returnValue: <_i14.BLEClientConnection>[],
            returnValueForMissingStub: <_i14.BLEClientConnection>[],
          )
          as List<_i14.BLEClientConnection>);

  @override
  List<_i12.BLEServerConnection> get serverConnections =>
      (super.noSuchMethod(
            Invocation.getter(#serverConnections),
            returnValue: <_i12.BLEServerConnection>[],
            returnValueForMissingStub: <_i12.BLEServerConnection>[],
          )
          as List<_i12.BLEServerConnection>);

  @override
  List<String> get connectedAddresses =>
      (super.noSuchMethod(
            Invocation.getter(#connectedAddresses),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get isNoHintDebounceActive =>
      (super.noSuchMethod(
            Invocation.getter(#isNoHintDebounceActive),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get activeConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get canAcceptMoreConnections =>
      (super.noSuchMethod(
            Invocation.getter(#canAcceptMoreConnections),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.Peripheral> get activeConnections =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnections),
            returnValue: <_i2.Peripheral>[],
            returnValueForMissingStub: <_i2.Peripheral>[],
          )
          as List<_i2.Peripheral>);

  @override
  int get maxClientConnections =>
      (super.noSuchMethod(
            Invocation.getter(#maxClientConnections),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  set onInboundDuplicateRejected(dynamic Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onInboundDuplicateRejected, value),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionChanged(dynamic Function(_i2.Peripheral?)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onConnectionChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onCharacteristicFound(dynamic Function(_i2.GATTCharacteristic?)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onCharacteristicFound, value),
        returnValueForMissingStub: null,
      );

  @override
  set onMtuDetected(dynamic Function(int?)? value) => super.noSuchMethod(
    Invocation.setter(#onMtuDetected, value),
    returnValueForMissingStub: null,
  );

  @override
  set onConnectionComplete(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onConnectionComplete, value),
    returnValueForMissingStub: null,
  );

  @override
  set onMonitoringChanged(dynamic Function(bool)? value) => super.noSuchMethod(
    Invocation.setter(#onMonitoringChanged, value),
    returnValueForMissingStub: null,
  );

  @override
  set onConnectionInfoChanged(dynamic Function(_i13.ConnectionInfo)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onConnectionInfoChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onCentralDisconnected(dynamic Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onCentralDisconnected, value),
        returnValueForMissingStub: null,
      );

  @override
  void setLocalHintProvider(_i4.Future<String?> Function()? provider) =>
      super.noSuchMethod(
        Invocation.method(#setLocalHintProvider, [provider]),
        returnValueForMissingStub: null,
      );

  @override
  bool isCollisionResolving(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#isCollisionResolving, [address]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isServerTeardownDeferred(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#isServerTeardownDeferred, [address]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void refreshPeerHintsFromDedup() => super.noSuchMethod(
    Invocation.method(#refreshPeerHintsFromDedup, []),
    returnValueForMissingStub: null,
  );

  @override
  void cachePeerHintForAddress(String? address, String? hint) =>
      super.noSuchMethod(
        Invocation.method(#cachePeerHintForAddress, [address, hint]),
        returnValueForMissingStub: null,
      );

  @override
  bool isResponderHandshakeBlocked(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#isResponderHandshakeBlocked, [address]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool hasAnyLinkForPeerHint(String? peerHint) =>
      (super.noSuchMethod(
            Invocation.method(#hasAnyLinkForPeerHint, [peerHint]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool hasClientLinkForPeer(String? peerAddress) =>
      (super.noSuchMethod(
            Invocation.method(#hasClientLinkForPeer, [peerAddress]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool hasServerLinkForPeer(String? peerAddress) =>
      (super.noSuchMethod(
            Invocation.method(#hasServerLinkForPeer, [peerAddress]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool hasPendingClientForPeer(String? peerAddress) =>
      (super.noSuchMethod(
            Invocation.method(#hasPendingClientForPeer, [peerAddress]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void startConnectionMonitoring() => super.noSuchMethod(
    Invocation.method(#startConnectionMonitoring, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopConnectionMonitoring() => super.noSuchMethod(
    Invocation.method(#stopConnectionMonitoring, []),
    returnValueForMissingStub: null,
  );

  @override
  void setPairingInProgress(bool? inProgress) => super.noSuchMethod(
    Invocation.method(#setPairingInProgress, [inProgress]),
    returnValueForMissingStub: null,
  );

  @override
  void setHandshakeInProgress(bool? inProgress) => super.noSuchMethod(
    Invocation.method(#setHandshakeInProgress, [inProgress]),
    returnValueForMissingStub: null,
  );

  @override
  void markHandshakeComplete() => super.noSuchMethod(
    Invocation.method(#markHandshakeComplete, []),
    returnValueForMissingStub: null,
  );

  @override
  void startHealthChecks() => super.noSuchMethod(
    Invocation.method(#startHealthChecks, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> startMeshNetworking({
    _i4.Future<void> Function()? onStartAdvertising,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startMeshNetworking, [], {
              #onStartAdvertising: onStartAdvertising,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopMeshNetworking() =>
      (super.noSuchMethod(
            Invocation.method(#stopMeshNetworking, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void handleCentralConnected(_i2.Central? central) => super.noSuchMethod(
    Invocation.method(#handleCentralConnected, [central]),
    returnValueForMissingStub: null,
  );

  @override
  void handleCentralDisconnected(_i2.Central? central) => super.noSuchMethod(
    Invocation.method(#handleCentralDisconnected, [central]),
    returnValueForMissingStub: null,
  );

  @override
  void handleCharacteristicSubscribed(
    _i2.Central? central,
    _i2.GATTCharacteristic? characteristic,
  ) => super.noSuchMethod(
    Invocation.method(#handleCharacteristicSubscribed, [
      central,
      characteristic,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void updateServerMtu(String? address, int? mtu) => super.noSuchMethod(
    Invocation.method(#updateServerMtu, [address, mtu]),
    returnValueForMissingStub: null,
  );

  @override
  bool hasServerConnection(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#hasServerConnection, [address]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> handlePowerModeChange(_i15.PowerMode? newMode) =>
      (super.noSuchMethod(
            Invocation.method(#handlePowerModeChange, [newMode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void handleBluetoothStateChange(_i2.BluetoothLowEnergyState? state) =>
      super.noSuchMethod(
        Invocation.method(#handleBluetoothStateChange, [state]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> connectToDevice(_i2.Peripheral? device, {int? rssi}) =>
      (super.noSuchMethod(
            Invocation.method(#connectToDevice, [device], {#rssi: rssi}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setMessageOperationInProgress(bool? inProgress) => super.noSuchMethod(
    Invocation.method(#setMessageOperationInProgress, [inProgress]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.Peripheral?> scanForSpecificDevice({
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scanForSpecificDevice, [], {#timeout: timeout}),
            returnValue: _i4.Future<_i2.Peripheral?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Peripheral?>.value(),
          )
          as _i4.Future<_i2.Peripheral?>);

  @override
  _i4.Future<void> disconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnectClient(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectClient, [address]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void triggerReconnection() => super.noSuchMethod(
    Invocation.method(#triggerReconnection, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearConnectionState({
    bool? keepMonitoring = false,
    String? contactId,
  }) => super.noSuchMethod(
    Invocation.method(#clearConnectionState, [], {
      #keepMonitoring: keepMonitoring,
      #contactId: contactId,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CentralManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCentralManager extends _i1.Mock implements _i2.CentralManager {
  @override
  _i4.Stream<_i2.DiscoveredEventArgs> get discovered =>
      (super.noSuchMethod(
            Invocation.getter(#discovered),
            returnValue: _i4.Stream<_i2.DiscoveredEventArgs>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i2.DiscoveredEventArgs>.empty(),
          )
          as _i4.Stream<_i2.DiscoveredEventArgs>);

  @override
  _i4.Stream<_i2.PeripheralConnectionStateChangedEventArgs>
  get connectionStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStateChanged),
            returnValue:
                _i4.Stream<
                  _i2.PeripheralConnectionStateChangedEventArgs
                >.empty(),
            returnValueForMissingStub:
                _i4.Stream<
                  _i2.PeripheralConnectionStateChangedEventArgs
                >.empty(),
          )
          as _i4.Stream<_i2.PeripheralConnectionStateChangedEventArgs>);

  @override
  _i4.Stream<_i2.PeripheralMTUChangedEventArgs> get mtuChanged =>
      (super.noSuchMethod(
            Invocation.getter(#mtuChanged),
            returnValue: _i4.Stream<_i2.PeripheralMTUChangedEventArgs>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i2.PeripheralMTUChangedEventArgs>.empty(),
          )
          as _i4.Stream<_i2.PeripheralMTUChangedEventArgs>);

  @override
  _i4.Stream<_i2.GATTCharacteristicNotifiedEventArgs>
  get characteristicNotified =>
      (super.noSuchMethod(
            Invocation.getter(#characteristicNotified),
            returnValue:
                _i4.Stream<_i2.GATTCharacteristicNotifiedEventArgs>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i2.GATTCharacteristicNotifiedEventArgs>.empty(),
          )
          as _i4.Stream<_i2.GATTCharacteristicNotifiedEventArgs>);

  @override
  _i2.BluetoothLowEnergyState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i2.BluetoothLowEnergyState.unknown,
            returnValueForMissingStub: _i2.BluetoothLowEnergyState.unknown,
          )
          as _i2.BluetoothLowEnergyState);

  @override
  _i4.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs> get stateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#stateChanged),
            returnValue:
                _i4.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs>.empty(),
          )
          as _i4.Stream<_i2.BluetoothLowEnergyStateChangedEventArgs>);

  @override
  _i4.Future<void> startDiscovery({List<_i2.UUID>? serviceUUIDs}) =>
      (super.noSuchMethod(
            Invocation.method(#startDiscovery, [], {
              #serviceUUIDs: serviceUUIDs,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Peripheral> getPeripheral(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getPeripheral, [address]),
            returnValue: _i4.Future<_i2.Peripheral>.value(
              _FakePeripheral_2(
                this,
                Invocation.method(#getPeripheral, [address]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Peripheral>.value(
              _FakePeripheral_2(
                this,
                Invocation.method(#getPeripheral, [address]),
              ),
            ),
          )
          as _i4.Future<_i2.Peripheral>);

  @override
  _i4.Future<List<_i2.Peripheral>> retrieveConnectedPeripherals() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveConnectedPeripherals, []),
            returnValue: _i4.Future<List<_i2.Peripheral>>.value(
              <_i2.Peripheral>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.Peripheral>>.value(
              <_i2.Peripheral>[],
            ),
          )
          as _i4.Future<List<_i2.Peripheral>>);

  @override
  _i4.Future<void> connect(_i2.Peripheral? peripheral) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [peripheral]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect(_i2.Peripheral? peripheral) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [peripheral]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> requestMTU(_i2.Peripheral? peripheral, {required int? mtu}) =>
      (super.noSuchMethod(
            Invocation.method(#requestMTU, [peripheral], {#mtu: mtu}),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getMaximumWriteLength(
    _i2.Peripheral? peripheral, {
    required _i2.GATTCharacteristicWriteType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMaximumWriteLength,
              [peripheral],
              {#type: type},
            ),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> readRSSI(_i2.Peripheral? peripheral) =>
      (super.noSuchMethod(
            Invocation.method(#readRSSI, [peripheral]),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i2.GATTService>> discoverGATT(_i2.Peripheral? peripheral) =>
      (super.noSuchMethod(
            Invocation.method(#discoverGATT, [peripheral]),
            returnValue: _i4.Future<List<_i2.GATTService>>.value(
              <_i2.GATTService>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.GATTService>>.value(
              <_i2.GATTService>[],
            ),
          )
          as _i4.Future<List<_i2.GATTService>>);

  @override
  _i4.Future<_i16.Uint8List> readCharacteristic(
    _i2.Peripheral? peripheral,
    _i2.GATTCharacteristic? characteristic,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readCharacteristic, [
              peripheral,
              characteristic,
            ]),
            returnValue: _i4.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
            returnValueForMissingStub: _i4.Future<_i16.Uint8List>.value(
              _i16.Uint8List(0),
            ),
          )
          as _i4.Future<_i16.Uint8List>);

  @override
  _i4.Future<void> writeCharacteristic(
    _i2.Peripheral? peripheral,
    _i2.GATTCharacteristic? characteristic, {
    required _i16.Uint8List? value,
    required _i2.GATTCharacteristicWriteType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeCharacteristic,
              [peripheral, characteristic],
              {#value: value, #type: type},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setCharacteristicNotifyState(
    _i2.Peripheral? peripheral,
    _i2.GATTCharacteristic? characteristic, {
    required bool? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setCharacteristicNotifyState,
              [peripheral, characteristic],
              {#state: state},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i16.Uint8List> readDescriptor(
    _i2.Peripheral? peripheral,
    _i2.GATTDescriptor? descriptor,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readDescriptor, [peripheral, descriptor]),
            returnValue: _i4.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
            returnValueForMissingStub: _i4.Future<_i16.Uint8List>.value(
              _i16.Uint8List(0),
            ),
          )
          as _i4.Future<_i16.Uint8List>);

  @override
  _i4.Future<void> writeDescriptor(
    _i2.Peripheral? peripheral,
    _i2.GATTDescriptor? descriptor, {
    required _i16.Uint8List? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeDescriptor,
              [peripheral, descriptor],
              {#value: value},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> authorize() =>
      (super.noSuchMethod(
            Invocation.method(#authorize, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> showAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#showAppSettings, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BluetoothStateMonitor].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluetoothStateMonitor extends _i1.Mock
    implements _i17.BluetoothStateMonitor {
  @override
  _i4.Stream<_i17.BluetoothStateInfo> get stateStream =>
      (super.noSuchMethod(
            Invocation.getter(#stateStream),
            returnValue: _i4.Stream<_i17.BluetoothStateInfo>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i17.BluetoothStateInfo>.empty(),
          )
          as _i4.Stream<_i17.BluetoothStateInfo>);

  @override
  _i4.Stream<_i17.BluetoothStatusMessage> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i4.Stream<_i17.BluetoothStatusMessage>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i17.BluetoothStatusMessage>.empty(),
          )
          as _i4.Stream<_i17.BluetoothStatusMessage>);

  @override
  _i2.BluetoothLowEnergyState get currentState =>
      (super.noSuchMethod(
            Invocation.getter(#currentState),
            returnValue: _i2.BluetoothLowEnergyState.unknown,
            returnValueForMissingStub: _i2.BluetoothLowEnergyState.unknown,
          )
          as _i2.BluetoothLowEnergyState);

  @override
  bool get isBluetoothReady =>
      (super.noSuchMethod(
            Invocation.getter(#isBluetoothReady),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> initialize({
    _i17.VoidCallback? onBluetoothReady,
    _i17.VoidCallback? onBluetoothUnavailable,
    _i17.VoidCallback? onInitializationRetry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #onBluetoothReady: onBluetoothReady,
              #onBluetoothUnavailable: onBluetoothUnavailable,
              #onInitializationRetry: onInitializationRetry,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> refreshState() =>
      (super.noSuchMethod(
            Invocation.method(#refreshState, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
