// Mocks generated by Mockito 5.4.6 from annotations
// in pak_connect/test/services/ble_handshake_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:pak_connect/core/models/protocol_message.dart' as _i6;
import 'package:pak_connect/core/models/spy_mode_info.dart' as _i5;
import 'package:pak_connect/core/services/security_manager.dart' as _i8;
import 'package:pak_connect/data/repositories/contact_repository.dart' as _i2;
import 'package:pak_connect/data/repositories/intro_hint_repository.dart'
    as _i9;
import 'package:pak_connect/data/services/ble_state_manager.dart' as _i3;
import 'package:pak_connect/domain/entities/ephemeral_discovery_hint.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeContactRepository_0 extends _i1.SmartFake
    implements _i2.ContactRepository {
  _FakeContactRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BLEStateManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBLEStateManager extends _i1.Mock implements _i3.BLEStateManager {
  @override
  bool get isPeripheralMode =>
      (super.noSuchMethod(
            Invocation.getter(#isPeripheralMode),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasContactRequest =>
      (super.noSuchMethod(
            Invocation.getter(#hasContactRequest),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get theyHaveUsAsContact =>
      (super.noSuchMethod(
            Invocation.getter(#theyHaveUsAsContact),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.ContactRepository get contactRepository =>
      (super.noSuchMethod(
            Invocation.getter(#contactRepository),
            returnValue: _FakeContactRepository_0(
              this,
              Invocation.getter(#contactRepository),
            ),
            returnValueForMissingStub: _FakeContactRepository_0(
              this,
              Invocation.getter(#contactRepository),
            ),
          )
          as _i2.ContactRepository);

  @override
  bool get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPaired =>
      (super.noSuchMethod(
            Invocation.getter(#isPaired),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<bool> get weHaveThemAsContact =>
      (super.noSuchMethod(
            Invocation.getter(#weHaveThemAsContact),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  set onSpyModeDetected(void Function(_i5.SpyModeInfo)? _onSpyModeDetected) =>
      super.noSuchMethod(
        Invocation.setter(#onSpyModeDetected, _onSpyModeDetected),
        returnValueForMissingStub: null,
      );

  @override
  set onIdentityRevealed(void Function(String)? _onIdentityRevealed) =>
      super.noSuchMethod(
        Invocation.setter(#onIdentityRevealed, _onIdentityRevealed),
        returnValueForMissingStub: null,
      );

  @override
  set onNameChanged(dynamic Function(String?)? _onNameChanged) =>
      super.noSuchMethod(
        Invocation.setter(#onNameChanged, _onNameChanged),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingCode(dynamic Function(String)? _onSendPairingCode) =>
      super.noSuchMethod(
        Invocation.setter(#onSendPairingCode, _onSendPairingCode),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingVerification(
    dynamic Function(String)? _onSendPairingVerification,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingVerification, _onSendPairingVerification),
    returnValueForMissingStub: null,
  );

  @override
  set onContactRequestReceived(
    dynamic Function(String, String)? _onContactRequestReceived,
  ) => super.noSuchMethod(
    Invocation.setter(#onContactRequestReceived, _onContactRequestReceived),
    returnValueForMissingStub: null,
  );

  @override
  set onContactRequestCompleted(
    dynamic Function(bool)? _onContactRequestCompleted,
  ) => super.noSuchMethod(
    Invocation.setter(#onContactRequestCompleted, _onContactRequestCompleted),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactRequest(
    dynamic Function(String, String)? _onSendContactRequest,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendContactRequest, _onSendContactRequest),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactAccept(
    dynamic Function(String, String)? _onSendContactAccept,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendContactAccept, _onSendContactAccept),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactReject(dynamic Function()? _onSendContactReject) =>
      super.noSuchMethod(
        Invocation.setter(#onSendContactReject, _onSendContactReject),
        returnValueForMissingStub: null,
      );

  @override
  set onSendContactStatus(
    dynamic Function(_i6.ProtocolMessage)? _onSendContactStatus,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendContactStatus, _onSendContactStatus),
    returnValueForMissingStub: null,
  );

  @override
  set onAsymmetricContactDetected(
    dynamic Function(String, String)? _onAsymmetricContactDetected,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onAsymmetricContactDetected,
      _onAsymmetricContactDetected,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onMutualConsentRequired(
    dynamic Function(String, String)? _onMutualConsentRequired,
  ) => super.noSuchMethod(
    Invocation.setter(#onMutualConsentRequired, _onMutualConsentRequired),
    returnValueForMissingStub: null,
  );

  @override
  set onMessageSent(dynamic Function(String, bool)? _onMessageSent) =>
      super.noSuchMethod(
        Invocation.setter(#onMessageSent, _onMessageSent),
        returnValueForMissingStub: null,
      );

  @override
  set onDeviceDiscovered(
    dynamic Function(dynamic, int?)? _onDeviceDiscovered,
  ) => super.noSuchMethod(
    Invocation.setter(#onDeviceDiscovered, _onDeviceDiscovered),
    returnValueForMissingStub: null,
  );

  @override
  set onMyUsernameChanged(dynamic Function(String)? _onMyUsernameChanged) =>
      super.noSuchMethod(
        Invocation.setter(#onMyUsernameChanged, _onMyUsernameChanged),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingRequest(
    dynamic Function(_i6.ProtocolMessage)? _onSendPairingRequest,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingRequest, _onSendPairingRequest),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPairingAccept(
    dynamic Function(_i6.ProtocolMessage)? _onSendPairingAccept,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingAccept, _onSendPairingAccept),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPairingCancel(
    dynamic Function(_i6.ProtocolMessage)? _onSendPairingCancel,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingCancel, _onSendPairingCancel),
    returnValueForMissingStub: null,
  );

  @override
  set onPairingRequestReceived(
    dynamic Function(String, String)? _onPairingRequestReceived,
  ) => super.noSuchMethod(
    Invocation.setter(#onPairingRequestReceived, _onPairingRequestReceived),
    returnValueForMissingStub: null,
  );

  @override
  set onPairingCancelled(dynamic Function()? _onPairingCancelled) =>
      super.noSuchMethod(
        Invocation.setter(#onPairingCancelled, _onPairingCancelled),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPersistentKeyExchange(
    dynamic Function(_i6.ProtocolMessage)? _onSendPersistentKeyExchange,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onSendPersistentKeyExchange,
      _onSendPersistentKeyExchange,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadUserName() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserName, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getMyPersistentId() =>
      (super.noSuchMethod(
            Invocation.method(#getMyPersistentId, []),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getMyPersistentId, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getMyPersistentId, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> setMyUserName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setMyUserName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setMyUserNameWithCallbacks(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setMyUserNameWithCallbacks, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setOtherUserName(String? name) => super.noSuchMethod(
    Invocation.method(#setOtherUserName, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void setOtherDeviceIdentity(String? deviceId, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#setOtherDeviceIdentity, [deviceId, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> saveContact(String? publicKey, String? userName) =>
      (super.noSuchMethod(
            Invocation.method(#saveContact, [publicKey, userName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Contact?> getContact(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContact, [publicKey]),
            returnValue: _i4.Future<_i2.Contact?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Contact?>.value(),
          )
          as _i4.Future<_i2.Contact?>);

  @override
  _i4.Future<Map<String, _i2.Contact>> getAllContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContacts, []),
            returnValue: _i4.Future<Map<String, _i2.Contact>>.value(
              <String, _i2.Contact>{},
            ),
            returnValueForMissingStub:
                _i4.Future<Map<String, _i2.Contact>>.value(
                  <String, _i2.Contact>{},
                ),
          )
          as _i4.Future<Map<String, _i2.Contact>>);

  @override
  _i4.Future<String?> getContactName(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactName, [publicKey]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> markContactVerified(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#markContactVerified, [publicKey]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.TrustStatus> getContactTrustStatus(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactTrustStatus, [publicKey]),
            returnValue: _i4.Future<_i2.TrustStatus>.value(
              _i2.TrustStatus.newContact,
            ),
            returnValueForMissingStub: _i4.Future<_i2.TrustStatus>.value(
              _i2.TrustStatus.newContact,
            ),
          )
          as _i4.Future<_i2.TrustStatus>);

  @override
  _i4.Future<bool> hasContactKeyChanged(
    String? publicKey,
    String? currentDisplayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasContactKeyChanged, [
              publicKey,
              currentDisplayName,
            ]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  String generatePairingCode() =>
      (super.noSuchMethod(
            Invocation.method(#generatePairingCode, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#generatePairingCode, []),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.method(#generatePairingCode, []),
            ),
          )
          as String);

  @override
  _i4.Future<bool> completePairing(String? theirCode) =>
      (super.noSuchMethod(
            Invocation.method(#completePairing, [theirCode]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void handleReceivedPairingCode(String? theirCode) => super.noSuchMethod(
    Invocation.method(#handleReceivedPairingCode, [theirCode]),
    returnValueForMissingStub: null,
  );

  @override
  void handlePairingVerification(String? theirSecretHash) => super.noSuchMethod(
    Invocation.method(#handlePairingVerification, [theirSecretHash]),
    returnValueForMissingStub: null,
  );

  @override
  void setTheirEphemeralId(String? ephemeralId, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#setTheirEphemeralId, [ephemeralId, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> sendPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#sendPairingRequest, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void handlePairingRequest(_i6.ProtocolMessage? message) => super.noSuchMethod(
    Invocation.method(#handlePairingRequest, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> acceptPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#acceptPairingRequest, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> rejectPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#rejectPairingRequest, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void handlePairingAccept(_i6.ProtocolMessage? message) => super.noSuchMethod(
    Invocation.method(#handlePairingAccept, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void handlePairingCancel(_i6.ProtocolMessage? message) => super.noSuchMethod(
    Invocation.method(#handlePairingCancel, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> cancelPairing({String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#cancelPairing, [], {#reason: reason}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> handlePersistentKeyExchange(String? theirPersistentKey) =>
      (super.noSuchMethod(
            Invocation.method(#handlePersistentKeyExchange, [
              theirPersistentKey,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.ProtocolMessage?> revealIdentityToFriend() =>
      (super.noSuchMethod(
            Invocation.method(#revealIdentityToFriend, []),
            returnValue: _i4.Future<_i6.ProtocolMessage?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.ProtocolMessage?>.value(),
          )
          as _i4.Future<_i6.ProtocolMessage?>);

  @override
  String? getPersistentKeyFromEphemeral(String? ephemeralId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersistentKeyFromEphemeral, [ephemeralId]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  String getIdType() =>
      (super.noSuchMethod(
            Invocation.method(#getIdType, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getIdType, []),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.method(#getIdType, []),
            ),
          )
          as String);

  @override
  void handleContactStatus(bool? theyHaveUsAsContact, String? theirPublicKey) =>
      super.noSuchMethod(
        Invocation.method(#handleContactStatus, [
          theyHaveUsAsContact,
          theirPublicKey,
        ]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> initializeContactFlags() =>
      (super.noSuchMethod(
            Invocation.method(#initializeContactFlags, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void preserveContactRelationship({
    String? otherPublicKey,
    String? otherName,
    bool? theyHaveUs,
    bool? weHaveThem,
  }) => super.noSuchMethod(
    Invocation.method(#preserveContactRelationship, [], {
      #otherPublicKey: otherPublicKey,
      #otherName: otherName,
      #theyHaveUs: theyHaveUs,
      #weHaveThem: weHaveThem,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> initiateContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#initiateContactRequest, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void handleContactRequestAcceptResponse(
    String? publicKey,
    String? displayName,
  ) => super.noSuchMethod(
    Invocation.method(#handleContactRequestAcceptResponse, [
      publicKey,
      displayName,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void handleContactRequestRejectResponse() => super.noSuchMethod(
    Invocation.method(#handleContactRequestRejectResponse, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> sendContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#sendContactRequest, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void updateTheirContactStatus(bool? theyHaveUs) => super.noSuchMethod(
    Invocation.method(#updateTheirContactStatus, [theyHaveUs]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> sendPairingCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#sendPairingCode, [code]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendPairingVerification(String? hash) =>
      (super.noSuchMethod(
            Invocation.method(#sendPairingVerification, [hash]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> checkExistingPairing(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#checkExistingPairing, [publicKey]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> handleContactRequest(
    String? publicKey,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleContactRequest, [publicKey, displayName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> acceptContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#acceptContactRequest, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void rejectContactRequest() => super.noSuchMethod(
    Invocation.method(#rejectContactRequest, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleContactAccept(String? publicKey, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#handleContactAccept, [publicKey, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> ensureContactMaximumSecurity(String? contactPublicKey) =>
      (super.noSuchMethod(
            Invocation.method(#ensureContactMaximumSecurity, [
              contactPublicKey,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void handleContactReject() => super.noSuchMethod(
    Invocation.method(#handleContactReject, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> checkForQRIntroduction(
    String? otherPublicKey,
    String? otherName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkForQRIntroduction, [
              otherPublicKey,
              otherName,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> requestSecurityLevelSync() =>
      (super.noSuchMethod(
            Invocation.method(#requestSecurityLevelSync, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> handleSecurityLevelSync(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
            Invocation.method(#handleSecurityLevelSync, [payload]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> confirmSecurityUpgrade(
    String? publicKey,
    _i8.SecurityLevel? newLevel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSecurityUpgrade, [publicKey, newLevel]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> resetContactSecurity(String? publicKey, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#resetContactSecurity, [publicKey, reason]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void updateTheirContactClaim(bool? theyClaimUs) => super.noSuchMethod(
    Invocation.method(#updateTheirContactClaim, [theyClaimUs]),
    returnValueForMissingStub: null,
  );

  @override
  void clearPairing() => super.noSuchMethod(
    Invocation.method(#clearPairing, []),
    returnValueForMissingStub: null,
  );

  @override
  String? getConversationKey(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationKey, [publicKey]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  void setPeripheralMode(bool? isPeripheral) => super.noSuchMethod(
    Invocation.method(#setPeripheralMode, [isPeripheral]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> requestContactStatusExchange() =>
      (super.noSuchMethod(
            Invocation.method(#requestContactStatusExchange, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearSessionState({bool? preservePersistentId = false}) =>
      super.noSuchMethod(
        Invocation.method(#clearSessionState, [], {
          #preservePersistentId: preservePersistentId,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void clearOtherUserName() => super.noSuchMethod(
    Invocation.method(#clearOtherUserName, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> recoverIdentityFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#recoverIdentityFromStorage, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String?>> getIdentityWithFallback() =>
      (super.noSuchMethod(
            Invocation.method(#getIdentityWithFallback, []),
            returnValue: _i4.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i4.Future<Map<String, String?>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IntroHintRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntroHintRepository extends _i1.Mock
    implements _i9.IntroHintRepository {
  @override
  _i4.Future<List<_i10.EphemeralDiscoveryHint>> getMyActiveHints() =>
      (super.noSuchMethod(
            Invocation.method(#getMyActiveHints, []),
            returnValue: _i4.Future<List<_i10.EphemeralDiscoveryHint>>.value(
              <_i10.EphemeralDiscoveryHint>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i10.EphemeralDiscoveryHint>>.value(
                  <_i10.EphemeralDiscoveryHint>[],
                ),
          )
          as _i4.Future<List<_i10.EphemeralDiscoveryHint>>);

  @override
  _i4.Future<void> saveMyActiveHint(_i10.EphemeralDiscoveryHint? hint) =>
      (super.noSuchMethod(
            Invocation.method(#saveMyActiveHint, [hint]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, _i10.EphemeralDiscoveryHint>> getScannedHints() =>
      (super.noSuchMethod(
            Invocation.method(#getScannedHints, []),
            returnValue:
                _i4.Future<Map<String, _i10.EphemeralDiscoveryHint>>.value(
                  <String, _i10.EphemeralDiscoveryHint>{},
                ),
            returnValueForMissingStub:
                _i4.Future<Map<String, _i10.EphemeralDiscoveryHint>>.value(
                  <String, _i10.EphemeralDiscoveryHint>{},
                ),
          )
          as _i4.Future<Map<String, _i10.EphemeralDiscoveryHint>>);

  @override
  _i4.Future<void> saveScannedHint(
    String? key,
    _i10.EphemeralDiscoveryHint? hint,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveScannedHint, [key, hint]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeScannedHint(String? hintHex) =>
      (super.noSuchMethod(
            Invocation.method(#removeScannedHint, [hintHex]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupExpiredHints() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupExpiredHints, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i10.EphemeralDiscoveryHint?> getMostRecentActiveHint() =>
      (super.noSuchMethod(
            Invocation.method(#getMostRecentActiveHint, []),
            returnValue: _i4.Future<_i10.EphemeralDiscoveryHint?>.value(),
            returnValueForMissingStub:
                _i4.Future<_i10.EphemeralDiscoveryHint?>.value(),
          )
          as _i4.Future<_i10.EphemeralDiscoveryHint?>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
