// Mocks generated by Mockito 5.4.6 from annotations
// in pak_connect/test/services/ble_messaging_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:typed_data' as _i13;

import 'package:bluetooth_low_energy/bluetooth_low_energy.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pak_connect/core/messaging/mesh_relay_engine.dart' as _i9;
import 'package:pak_connect/core/messaging/offline_message_queue.dart' as _i7;
import 'package:pak_connect/core/messaging/queue_sync_manager.dart' as _i8;
import 'package:pak_connect/core/models/connection_state.dart' as _i16;
import 'package:pak_connect/core/models/mesh_relay_models.dart' as _i6;
import 'package:pak_connect/core/models/protocol_message.dart' as _i10;
import 'package:pak_connect/core/models/spy_mode_info.dart' as _i20;
import 'package:pak_connect/core/power/adaptive_power_manager.dart' as _i19;
import 'package:pak_connect/core/services/security_manager.dart' as _i21;
import 'package:pak_connect/data/models/ble_client_connection.dart' as _i17;
import 'package:pak_connect/data/models/ble_server_connection.dart' as _i18;
import 'package:pak_connect/data/repositories/contact_repository.dart' as _i3;
import 'package:pak_connect/data/services/ble_connection_manager.dart' as _i15;
import 'package:pak_connect/data/services/ble_message_handler.dart' as _i4;
import 'package:pak_connect/data/services/ble_state_manager.dart' as _i12;
import 'package:pak_connect/domain/entities/enhanced_message.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCentralManager_0 extends _i1.SmartFake
    implements _i2.CentralManager {
  _FakeCentralManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeripheralManager_1 extends _i1.SmartFake
    implements _i2.PeripheralManager {
  _FakePeripheralManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContactRepository_2 extends _i1.SmartFake
    implements _i3.ContactRepository {
  _FakeContactRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BLEMessageHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockBLEMessageHandler extends _i1.Mock implements _i4.BLEMessageHandler {
  @override
  String get encryptionMethod =>
      (super.noSuchMethod(
            Invocation.getter(#encryptionMethod),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#encryptionMethod),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#encryptionMethod),
            ),
          )
          as String);

  @override
  set encryptionMethod(String? _encryptionMethod) => super.noSuchMethod(
    Invocation.setter(#encryptionMethod, _encryptionMethod),
    returnValueForMissingStub: null,
  );

  @override
  set onContactRequestReceived(
    dynamic Function(String, String)? _onContactRequestReceived,
  ) => super.noSuchMethod(
    Invocation.setter(#onContactRequestReceived, _onContactRequestReceived),
    returnValueForMissingStub: null,
  );

  @override
  set onContactAcceptReceived(
    dynamic Function(String, String)? _onContactAcceptReceived,
  ) => super.noSuchMethod(
    Invocation.setter(#onContactAcceptReceived, _onContactAcceptReceived),
    returnValueForMissingStub: null,
  );

  @override
  set onContactRejectReceived(dynamic Function()? _onContactRejectReceived) =>
      super.noSuchMethod(
        Invocation.setter(#onContactRejectReceived, _onContactRejectReceived),
        returnValueForMissingStub: null,
      );

  @override
  set onCryptoVerificationReceived(
    dynamic Function(String, String)? _onCryptoVerificationReceived,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onCryptoVerificationReceived,
      _onCryptoVerificationReceived,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onCryptoVerificationResponseReceived(
    dynamic Function(String, String, bool, Map<String, dynamic>?)?
    _onCryptoVerificationResponseReceived,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onCryptoVerificationResponseReceived,
      _onCryptoVerificationResponseReceived,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onQueueSyncReceived(
    dynamic Function(_i6.QueueSyncMessage, String)? _onQueueSyncReceived,
  ) => super.noSuchMethod(
    Invocation.setter(#onQueueSyncReceived, _onQueueSyncReceived),
    returnValueForMissingStub: null,
  );

  @override
  set onSendQueueMessages(
    dynamic Function(List<_i7.QueuedMessage>, String)? _onSendQueueMessages,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendQueueMessages, _onSendQueueMessages),
    returnValueForMissingStub: null,
  );

  @override
  set onQueueSyncCompleted(
    dynamic Function(String, _i8.QueueSyncResult)? _onQueueSyncCompleted,
  ) => super.noSuchMethod(
    Invocation.setter(#onQueueSyncCompleted, _onQueueSyncCompleted),
    returnValueForMissingStub: null,
  );

  @override
  set onRelayMessageReceived(
    dynamic Function(String, String, String)? _onRelayMessageReceived,
  ) => super.noSuchMethod(
    Invocation.setter(#onRelayMessageReceived, _onRelayMessageReceived),
    returnValueForMissingStub: null,
  );

  @override
  set onRelayDecisionMade(
    dynamic Function(_i9.RelayDecision)? _onRelayDecisionMade,
  ) => super.noSuchMethod(
    Invocation.setter(#onRelayDecisionMade, _onRelayDecisionMade),
    returnValueForMissingStub: null,
  );

  @override
  set onRelayStatsUpdated(
    dynamic Function(_i9.RelayStatistics)? _onRelayStatsUpdated,
  ) => super.noSuchMethod(
    Invocation.setter(#onRelayStatsUpdated, _onRelayStatsUpdated),
    returnValueForMissingStub: null,
  );

  @override
  set onSendAckMessage(
    dynamic Function(_i10.ProtocolMessage)? _onSendAckMessage,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendAckMessage, _onSendAckMessage),
    returnValueForMissingStub: null,
  );

  @override
  set onSendRelayMessage(
    dynamic Function(_i10.ProtocolMessage, String)? _onSendRelayMessage,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendRelayMessage, _onSendRelayMessage),
    returnValueForMissingStub: null,
  );

  @override
  set onIdentityRevealed(dynamic Function(String)? _onIdentityRevealed) =>
      super.noSuchMethod(
        Invocation.setter(#onIdentityRevealed, _onIdentityRevealed),
        returnValueForMissingStub: null,
      );

  @override
  void setCurrentNodeId(String? nodeId) => super.noSuchMethod(
    Invocation.method(#setCurrentNodeId, [nodeId]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> initializeRelaySystem({
    required String? currentNodeId,
    required _i7.OfflineMessageQueue? messageQueue,
    dynamic Function(String, String, String)? onRelayMessageReceived,
    dynamic Function(_i9.RelayDecision)? onRelayDecisionMade,
    dynamic Function(_i9.RelayStatistics)? onRelayStatsUpdated,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializeRelaySystem, [], {
              #currentNodeId: currentNodeId,
              #messageQueue: messageQueue,
              #onRelayMessageReceived: onRelayMessageReceived,
              #onRelayDecisionMade: onRelayDecisionMade,
              #onRelayStatsUpdated: onRelayStatsUpdated,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  List<String> getAvailableNextHops() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableNextHops, []),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i11.Future<bool> sendMessage({
    required _i2.CentralManager? centralManager,
    required _i2.Peripheral? connectedDevice,
    required _i2.GATTCharacteristic? messageCharacteristic,
    required String? message,
    required int? mtuSize,
    String? messageId,
    String? contactPublicKey,
    String? recipientId,
    bool? useEphemeralAddressing = false,
    String? originalIntendedRecipient,
    required _i3.ContactRepository? contactRepository,
    required _i12.BLEStateManager? stateManager,
    dynamic Function(bool)? onMessageOperationChanged,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #centralManager: centralManager,
              #connectedDevice: connectedDevice,
              #messageCharacteristic: messageCharacteristic,
              #message: message,
              #mtuSize: mtuSize,
              #messageId: messageId,
              #contactPublicKey: contactPublicKey,
              #recipientId: recipientId,
              #useEphemeralAddressing: useEphemeralAddressing,
              #originalIntendedRecipient: originalIntendedRecipient,
              #contactRepository: contactRepository,
              #stateManager: stateManager,
              #onMessageOperationChanged: onMessageOperationChanged,
            }),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> sendPeripheralMessage({
    required _i2.PeripheralManager? peripheralManager,
    required _i2.Central? connectedCentral,
    required _i2.GATTCharacteristic? messageCharacteristic,
    required String? message,
    required int? mtuSize,
    String? messageId,
    String? contactPublicKey,
    String? recipientId,
    bool? useEphemeralAddressing = false,
    String? originalIntendedRecipient,
    required _i3.ContactRepository? contactRepository,
    required _i12.BLEStateManager? stateManager,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPeripheralMessage, [], {
              #peripheralManager: peripheralManager,
              #connectedCentral: connectedCentral,
              #messageCharacteristic: messageCharacteristic,
              #message: message,
              #mtuSize: mtuSize,
              #messageId: messageId,
              #contactPublicKey: contactPublicKey,
              #recipientId: recipientId,
              #useEphemeralAddressing: useEphemeralAddressing,
              #originalIntendedRecipient: originalIntendedRecipient,
              #contactRepository: contactRepository,
              #stateManager: stateManager,
            }),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<String?> processReceivedData(
    _i13.Uint8List? data, {
    String? Function(String)? onMessageIdFound,
    String? senderPublicKey,
    required _i3.ContactRepository? contactRepository,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processReceivedData,
              [data],
              {
                #onMessageIdFound: onMessageIdFound,
                #senderPublicKey: senderPublicKey,
                #contactRepository: contactRepository,
              },
            ),
            returnValue: _i11.Future<String?>.value(),
            returnValueForMissingStub: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> handleQRIntroductionClaim({
    required String? otherPublicKey,
    required String? introId,
    required int? scannedTime,
    required String? theirName,
    required _i12.BLEStateManager? stateManager,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleQRIntroductionClaim, [], {
              #otherPublicKey: otherPublicKey,
              #introId: introId,
              #scannedTime: scannedTime,
              #theirName: theirName,
              #stateManager: stateManager,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> checkQRIntroductionMatch({
    required String? otherPublicKey,
    required String? theirName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkQRIntroductionMatch, [], {
              #otherPublicKey: otherPublicKey,
              #theirName: theirName,
            }),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> sendQueueSyncMessage({
    required _i2.CentralManager? centralManager,
    required _i2.PeripheralManager? peripheralManager,
    required _i2.Peripheral? connectedDevice,
    required _i2.Central? connectedCentral,
    required _i2.GATTCharacteristic? messageCharacteristic,
    required _i6.QueueSyncMessage? syncMessage,
    required int? mtuSize,
    required _i12.BLEStateManager? stateManager,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendQueueSyncMessage, [], {
              #centralManager: centralManager,
              #peripheralManager: peripheralManager,
              #connectedDevice: connectedDevice,
              #connectedCentral: connectedCentral,
              #messageCharacteristic: messageCharacteristic,
              #syncMessage: syncMessage,
              #mtuSize: mtuSize,
              #stateManager: stateManager,
            }),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<_i6.MeshRelayMessage?> createOutgoingRelay({
    required String? originalMessageId,
    required String? originalContent,
    required String? finalRecipientPublicKey,
    _i14.MessagePriority? priority = _i14.MessagePriority.normal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOutgoingRelay, [], {
              #originalMessageId: originalMessageId,
              #originalContent: originalContent,
              #finalRecipientPublicKey: finalRecipientPublicKey,
              #priority: priority,
            }),
            returnValue: _i11.Future<_i6.MeshRelayMessage?>.value(),
            returnValueForMissingStub:
                _i11.Future<_i6.MeshRelayMessage?>.value(),
          )
          as _i11.Future<_i6.MeshRelayMessage?>);

  @override
  _i11.Future<bool> shouldAttemptDecryption({
    required String? finalRecipientPublicKey,
    required String? originalSenderPublicKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shouldAttemptDecryption, [], {
              #finalRecipientPublicKey: finalRecipientPublicKey,
              #originalSenderPublicKey: originalSenderPublicKey,
            }),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BLEConnectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBLEConnectionManager extends _i1.Mock
    implements _i15.BLEConnectionManager {
  @override
  _i2.CentralManager get centralManager =>
      (super.noSuchMethod(
            Invocation.getter(#centralManager),
            returnValue: _FakeCentralManager_0(
              this,
              Invocation.getter(#centralManager),
            ),
            returnValueForMissingStub: _FakeCentralManager_0(
              this,
              Invocation.getter(#centralManager),
            ),
          )
          as _i2.CentralManager);

  @override
  _i2.PeripheralManager get peripheralManager =>
      (super.noSuchMethod(
            Invocation.getter(#peripheralManager),
            returnValue: _FakePeripheralManager_1(
              this,
              Invocation.getter(#peripheralManager),
            ),
            returnValueForMissingStub: _FakePeripheralManager_1(
              this,
              Invocation.getter(#peripheralManager),
            ),
          )
          as _i2.PeripheralManager);

  @override
  bool get hasBleConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasBleConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isReconnection =>
      (super.noSuchMethod(
            Invocation.getter(#isReconnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isMonitoring =>
      (super.noSuchMethod(
            Invocation.getter(#isMonitoring),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i16.ChatConnectionState get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i16.ChatConnectionState.disconnected,
            returnValueForMissingStub: _i16.ChatConnectionState.disconnected,
          )
          as _i16.ChatConnectionState);

  @override
  bool get isActivelyReconnecting =>
      (super.noSuchMethod(
            Invocation.getter(#isActivelyReconnecting),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isHealthChecking =>
      (super.noSuchMethod(
            Invocation.getter(#isHealthChecking),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get clientConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#clientConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get serverConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#serverConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get totalConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#totalConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get canAcceptClientConnection =>
      (super.noSuchMethod(
            Invocation.getter(#canAcceptClientConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canAcceptServerConnection =>
      (super.noSuchMethod(
            Invocation.getter(#canAcceptServerConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAdvertising =>
      (super.noSuchMethod(
            Invocation.getter(#isAdvertising),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i17.BLEClientConnection> get clientConnections =>
      (super.noSuchMethod(
            Invocation.getter(#clientConnections),
            returnValue: <_i17.BLEClientConnection>[],
            returnValueForMissingStub: <_i17.BLEClientConnection>[],
          )
          as List<_i17.BLEClientConnection>);

  @override
  List<_i18.BLEServerConnection> get serverConnections =>
      (super.noSuchMethod(
            Invocation.getter(#serverConnections),
            returnValue: <_i18.BLEServerConnection>[],
            returnValueForMissingStub: <_i18.BLEServerConnection>[],
          )
          as List<_i18.BLEServerConnection>);

  @override
  int get activeConnectionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnectionCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get canAcceptMoreConnections =>
      (super.noSuchMethod(
            Invocation.getter(#canAcceptMoreConnections),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.Peripheral> get activeConnections =>
      (super.noSuchMethod(
            Invocation.getter(#activeConnections),
            returnValue: <_i2.Peripheral>[],
            returnValueForMissingStub: <_i2.Peripheral>[],
          )
          as List<_i2.Peripheral>);

  @override
  int get maxClientConnections =>
      (super.noSuchMethod(
            Invocation.getter(#maxClientConnections),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  set onConnectionChanged(
    dynamic Function(_i2.Peripheral?)? _onConnectionChanged,
  ) => super.noSuchMethod(
    Invocation.setter(#onConnectionChanged, _onConnectionChanged),
    returnValueForMissingStub: null,
  );

  @override
  set onCharacteristicFound(
    dynamic Function(_i2.GATTCharacteristic?)? _onCharacteristicFound,
  ) => super.noSuchMethod(
    Invocation.setter(#onCharacteristicFound, _onCharacteristicFound),
    returnValueForMissingStub: null,
  );

  @override
  set onMtuDetected(dynamic Function(int?)? _onMtuDetected) =>
      super.noSuchMethod(
        Invocation.setter(#onMtuDetected, _onMtuDetected),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionComplete(dynamic Function()? _onConnectionComplete) =>
      super.noSuchMethod(
        Invocation.setter(#onConnectionComplete, _onConnectionComplete),
        returnValueForMissingStub: null,
      );

  @override
  set onMonitoringChanged(dynamic Function(bool)? _onMonitoringChanged) =>
      super.noSuchMethod(
        Invocation.setter(#onMonitoringChanged, _onMonitoringChanged),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionInfoChanged(
    dynamic Function(_i16.ConnectionInfo)? _onConnectionInfoChanged,
  ) => super.noSuchMethod(
    Invocation.setter(#onConnectionInfoChanged, _onConnectionInfoChanged),
    returnValueForMissingStub: null,
  );

  @override
  set onCentralDisconnected(dynamic Function(String)? _onCentralDisconnected) =>
      super.noSuchMethod(
        Invocation.setter(#onCentralDisconnected, _onCentralDisconnected),
        returnValueForMissingStub: null,
      );

  @override
  void setLocalHintProvider(_i11.Future<String?> Function()? provider) =>
      super.noSuchMethod(
        Invocation.method(#setLocalHintProvider, [provider]),
        returnValueForMissingStub: null,
      );

  @override
  void startConnectionMonitoring() => super.noSuchMethod(
    Invocation.method(#startConnectionMonitoring, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopConnectionMonitoring() => super.noSuchMethod(
    Invocation.method(#stopConnectionMonitoring, []),
    returnValueForMissingStub: null,
  );

  @override
  void setPairingInProgress(bool? inProgress) => super.noSuchMethod(
    Invocation.method(#setPairingInProgress, [inProgress]),
    returnValueForMissingStub: null,
  );

  @override
  void setHandshakeInProgress(bool? inProgress) => super.noSuchMethod(
    Invocation.method(#setHandshakeInProgress, [inProgress]),
    returnValueForMissingStub: null,
  );

  @override
  void startHealthChecks() => super.noSuchMethod(
    Invocation.method(#startHealthChecks, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> startMeshNetworking({
    _i11.Future<void> Function()? onStartAdvertising,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startMeshNetworking, [], {
              #onStartAdvertising: onStartAdvertising,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> stopMeshNetworking() =>
      (super.noSuchMethod(
            Invocation.method(#stopMeshNetworking, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void handleCentralConnected(_i2.Central? central) => super.noSuchMethod(
    Invocation.method(#handleCentralConnected, [central]),
    returnValueForMissingStub: null,
  );

  @override
  void handleCentralDisconnected(_i2.Central? central) => super.noSuchMethod(
    Invocation.method(#handleCentralDisconnected, [central]),
    returnValueForMissingStub: null,
  );

  @override
  void handleCharacteristicSubscribed(
    _i2.Central? central,
    _i2.GATTCharacteristic? characteristic,
  ) => super.noSuchMethod(
    Invocation.method(#handleCharacteristicSubscribed, [
      central,
      characteristic,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> handlePowerModeChange(_i19.PowerMode? newMode) =>
      (super.noSuchMethod(
            Invocation.method(#handlePowerModeChange, [newMode]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void handleBluetoothStateChange(_i2.BluetoothLowEnergyState? state) =>
      super.noSuchMethod(
        Invocation.method(#handleBluetoothStateChange, [state]),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> connectToDevice(_i2.Peripheral? device, {int? rssi}) =>
      (super.noSuchMethod(
            Invocation.method(#connectToDevice, [device], {#rssi: rssi}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void setMessageOperationInProgress(bool? inProgress) => super.noSuchMethod(
    Invocation.method(#setMessageOperationInProgress, [inProgress]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i2.Peripheral?> scanForSpecificDevice({
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scanForSpecificDevice, [], {#timeout: timeout}),
            returnValue: _i11.Future<_i2.Peripheral?>.value(),
            returnValueForMissingStub: _i11.Future<_i2.Peripheral?>.value(),
          )
          as _i11.Future<_i2.Peripheral?>);

  @override
  _i11.Future<void> disconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#disconnectAll, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> disconnectClient(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectClient, [address]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void triggerReconnection() => super.noSuchMethod(
    Invocation.method(#triggerReconnection, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearConnectionState({
    bool? keepMonitoring = false,
    String? contactId,
  }) => super.noSuchMethod(
    Invocation.method(#clearConnectionState, [], {
      #keepMonitoring: keepMonitoring,
      #contactId: contactId,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BLEStateManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBLEStateManager extends _i1.Mock implements _i12.BLEStateManager {
  @override
  bool get isPeripheralMode =>
      (super.noSuchMethod(
            Invocation.getter(#isPeripheralMode),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasContactRequest =>
      (super.noSuchMethod(
            Invocation.getter(#hasContactRequest),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get theyHaveUsAsContact =>
      (super.noSuchMethod(
            Invocation.getter(#theyHaveUsAsContact),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.ContactRepository get contactRepository =>
      (super.noSuchMethod(
            Invocation.getter(#contactRepository),
            returnValue: _FakeContactRepository_2(
              this,
              Invocation.getter(#contactRepository),
            ),
            returnValueForMissingStub: _FakeContactRepository_2(
              this,
              Invocation.getter(#contactRepository),
            ),
          )
          as _i3.ContactRepository);

  @override
  bool get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPaired =>
      (super.noSuchMethod(
            Invocation.getter(#isPaired),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i11.Future<bool> get weHaveThemAsContact =>
      (super.noSuchMethod(
            Invocation.getter(#weHaveThemAsContact),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  set onSpyModeDetected(void Function(_i20.SpyModeInfo)? _onSpyModeDetected) =>
      super.noSuchMethod(
        Invocation.setter(#onSpyModeDetected, _onSpyModeDetected),
        returnValueForMissingStub: null,
      );

  @override
  set onIdentityRevealed(void Function(String)? _onIdentityRevealed) =>
      super.noSuchMethod(
        Invocation.setter(#onIdentityRevealed, _onIdentityRevealed),
        returnValueForMissingStub: null,
      );

  @override
  set onNameChanged(dynamic Function(String?)? _onNameChanged) =>
      super.noSuchMethod(
        Invocation.setter(#onNameChanged, _onNameChanged),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingCode(dynamic Function(String)? _onSendPairingCode) =>
      super.noSuchMethod(
        Invocation.setter(#onSendPairingCode, _onSendPairingCode),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingVerification(
    dynamic Function(String)? _onSendPairingVerification,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingVerification, _onSendPairingVerification),
    returnValueForMissingStub: null,
  );

  @override
  set onContactRequestReceived(
    dynamic Function(String, String)? _onContactRequestReceived,
  ) => super.noSuchMethod(
    Invocation.setter(#onContactRequestReceived, _onContactRequestReceived),
    returnValueForMissingStub: null,
  );

  @override
  set onContactRequestCompleted(
    dynamic Function(bool)? _onContactRequestCompleted,
  ) => super.noSuchMethod(
    Invocation.setter(#onContactRequestCompleted, _onContactRequestCompleted),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactRequest(
    dynamic Function(String, String)? _onSendContactRequest,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendContactRequest, _onSendContactRequest),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactAccept(
    dynamic Function(String, String)? _onSendContactAccept,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendContactAccept, _onSendContactAccept),
    returnValueForMissingStub: null,
  );

  @override
  set onSendContactReject(dynamic Function()? _onSendContactReject) =>
      super.noSuchMethod(
        Invocation.setter(#onSendContactReject, _onSendContactReject),
        returnValueForMissingStub: null,
      );

  @override
  set onSendContactStatus(
    dynamic Function(_i10.ProtocolMessage)? _onSendContactStatus,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendContactStatus, _onSendContactStatus),
    returnValueForMissingStub: null,
  );

  @override
  set onAsymmetricContactDetected(
    dynamic Function(String, String)? _onAsymmetricContactDetected,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onAsymmetricContactDetected,
      _onAsymmetricContactDetected,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onMutualConsentRequired(
    dynamic Function(String, String)? _onMutualConsentRequired,
  ) => super.noSuchMethod(
    Invocation.setter(#onMutualConsentRequired, _onMutualConsentRequired),
    returnValueForMissingStub: null,
  );

  @override
  set onMessageSent(dynamic Function(String, bool)? _onMessageSent) =>
      super.noSuchMethod(
        Invocation.setter(#onMessageSent, _onMessageSent),
        returnValueForMissingStub: null,
      );

  @override
  set onDeviceDiscovered(
    dynamic Function(dynamic, int?)? _onDeviceDiscovered,
  ) => super.noSuchMethod(
    Invocation.setter(#onDeviceDiscovered, _onDeviceDiscovered),
    returnValueForMissingStub: null,
  );

  @override
  set onMyUsernameChanged(dynamic Function(String)? _onMyUsernameChanged) =>
      super.noSuchMethod(
        Invocation.setter(#onMyUsernameChanged, _onMyUsernameChanged),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPairingRequest(
    dynamic Function(_i10.ProtocolMessage)? _onSendPairingRequest,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingRequest, _onSendPairingRequest),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPairingAccept(
    dynamic Function(_i10.ProtocolMessage)? _onSendPairingAccept,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingAccept, _onSendPairingAccept),
    returnValueForMissingStub: null,
  );

  @override
  set onSendPairingCancel(
    dynamic Function(_i10.ProtocolMessage)? _onSendPairingCancel,
  ) => super.noSuchMethod(
    Invocation.setter(#onSendPairingCancel, _onSendPairingCancel),
    returnValueForMissingStub: null,
  );

  @override
  set onPairingRequestReceived(
    dynamic Function(String, String)? _onPairingRequestReceived,
  ) => super.noSuchMethod(
    Invocation.setter(#onPairingRequestReceived, _onPairingRequestReceived),
    returnValueForMissingStub: null,
  );

  @override
  set onPairingCancelled(dynamic Function()? _onPairingCancelled) =>
      super.noSuchMethod(
        Invocation.setter(#onPairingCancelled, _onPairingCancelled),
        returnValueForMissingStub: null,
      );

  @override
  set onSendPersistentKeyExchange(
    dynamic Function(_i10.ProtocolMessage)? _onSendPersistentKeyExchange,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onSendPersistentKeyExchange,
      _onSendPersistentKeyExchange,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> loadUserName() =>
      (super.noSuchMethod(
            Invocation.method(#loadUserName, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String> getMyPersistentId() =>
      (super.noSuchMethod(
            Invocation.method(#getMyPersistentId, []),
            returnValue: _i11.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getMyPersistentId, []),
              ),
            ),
            returnValueForMissingStub: _i11.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getMyPersistentId, []),
              ),
            ),
          )
          as _i11.Future<String>);

  @override
  _i11.Future<void> setMyUserName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setMyUserName, [name]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setMyUserNameWithCallbacks(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setMyUserNameWithCallbacks, [name]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void setOtherUserName(String? name) => super.noSuchMethod(
    Invocation.method(#setOtherUserName, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void setOtherDeviceIdentity(String? deviceId, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#setOtherDeviceIdentity, [deviceId, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> saveContact(String? publicKey, String? userName) =>
      (super.noSuchMethod(
            Invocation.method(#saveContact, [publicKey, userName]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i3.Contact?> getContact(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContact, [publicKey]),
            returnValue: _i11.Future<_i3.Contact?>.value(),
            returnValueForMissingStub: _i11.Future<_i3.Contact?>.value(),
          )
          as _i11.Future<_i3.Contact?>);

  @override
  _i11.Future<Map<String, _i3.Contact>> getAllContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContacts, []),
            returnValue: _i11.Future<Map<String, _i3.Contact>>.value(
              <String, _i3.Contact>{},
            ),
            returnValueForMissingStub:
                _i11.Future<Map<String, _i3.Contact>>.value(
                  <String, _i3.Contact>{},
                ),
          )
          as _i11.Future<Map<String, _i3.Contact>>);

  @override
  _i11.Future<String?> getContactName(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactName, [publicKey]),
            returnValue: _i11.Future<String?>.value(),
            returnValueForMissingStub: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> markContactVerified(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#markContactVerified, [publicKey]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i3.TrustStatus> getContactTrustStatus(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactTrustStatus, [publicKey]),
            returnValue: _i11.Future<_i3.TrustStatus>.value(
              _i3.TrustStatus.newContact,
            ),
            returnValueForMissingStub: _i11.Future<_i3.TrustStatus>.value(
              _i3.TrustStatus.newContact,
            ),
          )
          as _i11.Future<_i3.TrustStatus>);

  @override
  _i11.Future<bool> hasContactKeyChanged(
    String? publicKey,
    String? currentDisplayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasContactKeyChanged, [
              publicKey,
              currentDisplayName,
            ]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  String generatePairingCode() =>
      (super.noSuchMethod(
            Invocation.method(#generatePairingCode, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#generatePairingCode, []),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#generatePairingCode, []),
            ),
          )
          as String);

  @override
  _i11.Future<bool> completePairing(String? theirCode) =>
      (super.noSuchMethod(
            Invocation.method(#completePairing, [theirCode]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void handleReceivedPairingCode(String? theirCode) => super.noSuchMethod(
    Invocation.method(#handleReceivedPairingCode, [theirCode]),
    returnValueForMissingStub: null,
  );

  @override
  void handlePairingVerification(String? theirSecretHash) => super.noSuchMethod(
    Invocation.method(#handlePairingVerification, [theirSecretHash]),
    returnValueForMissingStub: null,
  );

  @override
  void setTheirEphemeralId(String? ephemeralId, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#setTheirEphemeralId, [ephemeralId, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> sendPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#sendPairingRequest, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void handlePairingRequest(_i10.ProtocolMessage? message) =>
      super.noSuchMethod(
        Invocation.method(#handlePairingRequest, [message]),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> acceptPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#acceptPairingRequest, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> rejectPairingRequest() =>
      (super.noSuchMethod(
            Invocation.method(#rejectPairingRequest, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void handlePairingAccept(_i10.ProtocolMessage? message) => super.noSuchMethod(
    Invocation.method(#handlePairingAccept, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void handlePairingCancel(_i10.ProtocolMessage? message) => super.noSuchMethod(
    Invocation.method(#handlePairingCancel, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> cancelPairing({String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#cancelPairing, [], {#reason: reason}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> handlePersistentKeyExchange(String? theirPersistentKey) =>
      (super.noSuchMethod(
            Invocation.method(#handlePersistentKeyExchange, [
              theirPersistentKey,
            ]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i10.ProtocolMessage?> revealIdentityToFriend() =>
      (super.noSuchMethod(
            Invocation.method(#revealIdentityToFriend, []),
            returnValue: _i11.Future<_i10.ProtocolMessage?>.value(),
            returnValueForMissingStub:
                _i11.Future<_i10.ProtocolMessage?>.value(),
          )
          as _i11.Future<_i10.ProtocolMessage?>);

  @override
  String? getPersistentKeyFromEphemeral(String? ephemeralId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersistentKeyFromEphemeral, [ephemeralId]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  String getIdType() =>
      (super.noSuchMethod(
            Invocation.method(#getIdType, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getIdType, []),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#getIdType, []),
            ),
          )
          as String);

  @override
  void handleContactStatus(bool? theyHaveUsAsContact, String? theirPublicKey) =>
      super.noSuchMethod(
        Invocation.method(#handleContactStatus, [
          theyHaveUsAsContact,
          theirPublicKey,
        ]),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> initializeContactFlags() =>
      (super.noSuchMethod(
            Invocation.method(#initializeContactFlags, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void preserveContactRelationship({
    String? otherPublicKey,
    String? otherName,
    bool? theyHaveUs,
    bool? weHaveThem,
  }) => super.noSuchMethod(
    Invocation.method(#preserveContactRelationship, [], {
      #otherPublicKey: otherPublicKey,
      #otherName: otherName,
      #theyHaveUs: theyHaveUs,
      #weHaveThem: weHaveThem,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<bool> initiateContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#initiateContactRequest, []),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void handleContactRequestAcceptResponse(
    String? publicKey,
    String? displayName,
  ) => super.noSuchMethod(
    Invocation.method(#handleContactRequestAcceptResponse, [
      publicKey,
      displayName,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void handleContactRequestRejectResponse() => super.noSuchMethod(
    Invocation.method(#handleContactRequestRejectResponse, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<bool> sendContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#sendContactRequest, []),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void updateTheirContactStatus(bool? theyHaveUs) => super.noSuchMethod(
    Invocation.method(#updateTheirContactStatus, [theyHaveUs]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> sendPairingCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#sendPairingCode, [code]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> sendPairingVerification(String? hash) =>
      (super.noSuchMethod(
            Invocation.method(#sendPairingVerification, [hash]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> checkExistingPairing(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#checkExistingPairing, [publicKey]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> handleContactRequest(
    String? publicKey,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleContactRequest, [publicKey, displayName]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> acceptContactRequest() =>
      (super.noSuchMethod(
            Invocation.method(#acceptContactRequest, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void rejectContactRequest() => super.noSuchMethod(
    Invocation.method(#rejectContactRequest, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleContactAccept(String? publicKey, String? displayName) =>
      super.noSuchMethod(
        Invocation.method(#handleContactAccept, [publicKey, displayName]),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> ensureContactMaximumSecurity(String? contactPublicKey) =>
      (super.noSuchMethod(
            Invocation.method(#ensureContactMaximumSecurity, [
              contactPublicKey,
            ]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void handleContactReject() => super.noSuchMethod(
    Invocation.method(#handleContactReject, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> checkForQRIntroduction(
    String? otherPublicKey,
    String? otherName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkForQRIntroduction, [
              otherPublicKey,
              otherName,
            ]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> requestSecurityLevelSync() =>
      (super.noSuchMethod(
            Invocation.method(#requestSecurityLevelSync, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> handleSecurityLevelSync(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
            Invocation.method(#handleSecurityLevelSync, [payload]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> confirmSecurityUpgrade(
    String? publicKey,
    _i21.SecurityLevel? newLevel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSecurityUpgrade, [publicKey, newLevel]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> resetContactSecurity(String? publicKey, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#resetContactSecurity, [publicKey, reason]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void updateTheirContactClaim(bool? theyClaimUs) => super.noSuchMethod(
    Invocation.method(#updateTheirContactClaim, [theyClaimUs]),
    returnValueForMissingStub: null,
  );

  @override
  void clearPairing() => super.noSuchMethod(
    Invocation.method(#clearPairing, []),
    returnValueForMissingStub: null,
  );

  @override
  String? getConversationKey(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationKey, [publicKey]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  void setPeripheralMode(bool? isPeripheral) => super.noSuchMethod(
    Invocation.method(#setPeripheralMode, [isPeripheral]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> requestContactStatusExchange() =>
      (super.noSuchMethod(
            Invocation.method(#requestContactStatusExchange, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void clearSessionState({bool? preservePersistentId = false}) =>
      super.noSuchMethod(
        Invocation.method(#clearSessionState, [], {
          #preservePersistentId: preservePersistentId,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void clearOtherUserName() => super.noSuchMethod(
    Invocation.method(#clearOtherUserName, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> recoverIdentityFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#recoverIdentityFromStorage, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<Map<String, String?>> getIdentityWithFallback() =>
      (super.noSuchMethod(
            Invocation.method(#getIdentityWithFallback, []),
            returnValue: _i11.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
            returnValueForMissingStub: _i11.Future<Map<String, String?>>.value(
              <String, String?>{},
            ),
          )
          as _i11.Future<Map<String, String?>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
