@echo off
setlocal enabledelayedexpansion

:: Get current directory name for the output file
for %%I in (.) do set "CURRENT_DIR=%%~nxI"

:: Set output file name
set "OUTPUT_FILE=folder_structure_%CURRENT_DIR%.md"

:: Create/overwrite the output file
echo # Project Structure: %CURRENT_DIR% > "%OUTPUT_FILE%"
echo. >> "%OUTPUT_FILE%"
echo Generated on: %date% %time% >> "%OUTPUT_FILE%"
echo Location: %CD% >> "%OUTPUT_FILE%"
echo. >> "%OUTPUT_FILE%"
echo ```tree >> "%OUTPUT_FILE%"

:: Use tree command to generate structure
tree /F /A >> "%OUTPUT_FILE%"

echo ``` >> "%OUTPUT_FILE%"
echo. >> "%OUTPUT_FILE%"

:: Add detailed file list with extensions
echo ## Detailed File List >> "%OUTPUT_FILE%"
echo. >> "%OUTPUT_FILE%"

:: Create detailed list using dir command
echo ### Files by Directory >> "%OUTPUT_FILE%"
echo. >> "%OUTPUT_FILE%"

for /f "delims=" %%d in ('dir /b /ad /s') do (
    echo. >> "%OUTPUT_FILE%"
    echo **%%d** >> "%OUTPUT_FILE%"
    for /f "delims=" %%f in ('dir "%%d" /b /a-d 2^>nul') do (
        echo - %%f >> "%OUTPUT_FILE%"
    )
)

:: Add root directory files
echo. >> "%OUTPUT_FILE%"
echo **%CD% (Root)** >> "%OUTPUT_FILE%"
for /f "delims=" %%f in ('dir /b /a-d') do (
    echo - %%f >> "%OUTPUT_FILE%"
)

echo. >> "%OUTPUT_FILE%"
echo ---
echo **Generated by folder_structure.bat**

:: Notify user
echo.
echo ====================================
echo Folder structure saved to: %OUTPUT_FILE%
echo ====================================
echo.
echo File contains:
echo - Tree view of all folders and files
echo - Detailed file list by directory
echo - Markdown formatting for easy reading
echo.
pause