// Mocks generated by Mockito 5.4.6 from annotations
// in pak_connect/test/domain/services/chat_management_service_static_config_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bluetooth_low_energy/bluetooth_low_energy.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pak_connect/domain/entities/archived_chat.dart' as _i14;
import 'package:pak_connect/domain/entities/chat_list_item.dart' as _i7;
import 'package:pak_connect/domain/entities/contact.dart' as _i9;
import 'package:pak_connect/domain/entities/message.dart' as _i12;
import 'package:pak_connect/domain/interfaces/i_archive_repository.dart'
    as _i13;
import 'package:pak_connect/domain/interfaces/i_chats_repository.dart' as _i5;
import 'package:pak_connect/domain/interfaces/i_message_repository.dart'
    as _i11;
import 'package:pak_connect/domain/models/archive_models.dart' as _i2;
import 'package:pak_connect/domain/services/archive_management_models.dart'
    as _i3;
import 'package:pak_connect/domain/services/archive_management_service.dart'
    as _i15;
import 'package:pak_connect/domain/services/archive_search_models.dart' as _i4;
import 'package:pak_connect/domain/services/archive_search_service.dart'
    as _i16;
import 'package:pak_connect/domain/values/id_types.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeArchiveOperationResult_0 extends _i1.SmartFake
    implements _i2.ArchiveOperationResult {
  _FakeArchiveOperationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArchiveSearchResult_1 extends _i1.SmartFake
    implements _i2.ArchiveSearchResult {
  _FakeArchiveSearchResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArchiveManagementConfig_2 extends _i1.SmartFake
    implements _i3.ArchiveManagementConfig {
  _FakeArchiveManagementConfig_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArchivePolicyResult_3 extends _i1.SmartFake
    implements _i3.ArchivePolicyResult {
  _FakeArchivePolicyResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArchiveMaintenanceResult_4 extends _i1.SmartFake
    implements _i3.ArchiveMaintenanceResult {
  _FakeArchiveMaintenanceResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArchiveAnalytics_5 extends _i1.SmartFake
    implements _i3.ArchiveAnalytics {
  _FakeArchiveAnalytics_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArchiveHealthStatus_6 extends _i1.SmartFake
    implements _i3.ArchiveHealthStatus {
  _FakeArchiveHealthStatus_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchServiceConfig_7 extends _i1.SmartFake
    implements _i4.SearchServiceConfig {
  _FakeSearchServiceConfig_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdvancedSearchResult_8 extends _i1.SmartFake
    implements _i4.AdvancedSearchResult {
  _FakeAdvancedSearchResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchAnalyticsReport_9 extends _i1.SmartFake
    implements _i4.SearchAnalyticsReport {
  _FakeSearchAnalyticsReport_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IChatsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChatsRepository extends _i1.Mock implements _i5.IChatsRepository {
  MockIChatsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i7.ChatListItem>> getAllChats({
    List<_i8.Peripheral>? nearbyDevices,
    Map<String, _i8.DiscoveredEventArgs>? discoveryData,
    String? searchQuery,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllChats, [], {
              #nearbyDevices: nearbyDevices,
              #discoveryData: discoveryData,
              #searchQuery: searchQuery,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i6.Future<List<_i7.ChatListItem>>.value(
              <_i7.ChatListItem>[],
            ),
          )
          as _i6.Future<List<_i7.ChatListItem>>);

  @override
  _i6.Future<List<_i9.Contact>> getContactsWithoutChats() =>
      (super.noSuchMethod(
            Invocation.method(#getContactsWithoutChats, []),
            returnValue: _i6.Future<List<_i9.Contact>>.value(<_i9.Contact>[]),
          )
          as _i6.Future<List<_i9.Contact>>);

  @override
  _i6.Future<void> markChatAsRead(_i10.ChatId? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#markChatAsRead, [chatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> incrementUnreadCount(_i10.ChatId? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementUnreadCount, [chatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateContactLastSeen(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#updateContactLastSeen, [publicKey]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getTotalUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalUnreadCount, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> storeDeviceMapping(String? deviceUuid, String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#storeDeviceMapping, [deviceUuid, publicKey]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getChatCount() =>
      (super.noSuchMethod(
            Invocation.method(#getChatCount, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> getArchivedChatCount() =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedChatCount, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> getTotalMessageCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalMessageCount, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> cleanupOrphanedEphemeralContacts() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOrphanedEphemeralContacts, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}

/// A class which mocks [IMessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMessageRepository extends _i1.Mock
    implements _i11.IMessageRepository {
  MockIMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i12.Message>> getMessages(_i10.ChatId? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [chatId]),
            returnValue: _i6.Future<List<_i12.Message>>.value(<_i12.Message>[]),
          )
          as _i6.Future<List<_i12.Message>>);

  @override
  _i6.Future<_i12.Message?> getMessageById(_i10.MessageId? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [messageId]),
            returnValue: _i6.Future<_i12.Message?>.value(),
          )
          as _i6.Future<_i12.Message?>);

  @override
  _i6.Future<void> saveMessage(_i12.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessage, [message]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateMessage(_i12.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessage, [message]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearMessages(_i10.ChatId? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#clearMessages, [chatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> deleteMessage(_i10.MessageId? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i12.Message>> getAllMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMessages, []),
            returnValue: _i6.Future<List<_i12.Message>>.value(<_i12.Message>[]),
          )
          as _i6.Future<List<_i12.Message>>);

  @override
  _i6.Future<List<_i12.Message>> getMessagesForContact(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesForContact, [publicKey]),
            returnValue: _i6.Future<List<_i12.Message>>.value(<_i12.Message>[]),
          )
          as _i6.Future<List<_i12.Message>>);

  @override
  _i6.Future<void> migrateChatId(
    _i10.ChatId? oldChatId,
    _i10.ChatId? newChatId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#migrateChatId, [oldChatId, newChatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [IArchiveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIArchiveRepository extends _i1.Mock
    implements _i13.IArchiveRepository {
  MockIArchiveRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.ArchiveOperationResult> archiveChat({
    required String? chatId,
    String? archiveReason,
    Map<String, dynamic>? customData,
    bool? compressLargeArchives = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#archiveChat, [], {
              #chatId: chatId,
              #archiveReason: archiveReason,
              #customData: customData,
              #compressLargeArchives: compressLargeArchives,
            }),
            returnValue: _i6.Future<_i2.ArchiveOperationResult>.value(
              _FakeArchiveOperationResult_0(
                this,
                Invocation.method(#archiveChat, [], {
                  #chatId: chatId,
                  #archiveReason: archiveReason,
                  #customData: customData,
                  #compressLargeArchives: compressLargeArchives,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ArchiveOperationResult>);

  @override
  _i6.Future<_i2.ArchiveOperationResult> restoreChat(
    _i10.ArchiveId? archiveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restoreChat, [archiveId]),
            returnValue: _i6.Future<_i2.ArchiveOperationResult>.value(
              _FakeArchiveOperationResult_0(
                this,
                Invocation.method(#restoreChat, [archiveId]),
              ),
            ),
          )
          as _i6.Future<_i2.ArchiveOperationResult>);

  @override
  _i6.Future<int> getArchivedChatsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedChatsCount, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i14.ArchivedChatSummary>> getArchivedChats({
    _i2.ArchiveSearchFilter? filter,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedChats, [], {
              #filter: filter,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i6.Future<List<_i14.ArchivedChatSummary>>.value(
              <_i14.ArchivedChatSummary>[],
            ),
          )
          as _i6.Future<List<_i14.ArchivedChatSummary>>);

  @override
  _i6.Future<_i14.ArchivedChatSummary?> getArchivedChatByOriginalId(
    String? chatId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedChatByOriginalId, [chatId]),
            returnValue: _i6.Future<_i14.ArchivedChatSummary?>.value(),
          )
          as _i6.Future<_i14.ArchivedChatSummary?>);

  @override
  _i6.Future<_i14.ArchivedChat?> getArchivedChat(_i10.ArchiveId? archiveId) =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedChat, [archiveId]),
            returnValue: _i6.Future<_i14.ArchivedChat?>.value(),
          )
          as _i6.Future<_i14.ArchivedChat?>);

  @override
  _i6.Future<_i2.ArchiveSearchResult> searchArchives({
    required String? query,
    _i2.ArchiveSearchFilter? filter,
    int? limit,
    String? afterCursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchArchives, [], {
              #query: query,
              #filter: filter,
              #limit: limit,
              #afterCursor: afterCursor,
            }),
            returnValue: _i6.Future<_i2.ArchiveSearchResult>.value(
              _FakeArchiveSearchResult_1(
                this,
                Invocation.method(#searchArchives, [], {
                  #query: query,
                  #filter: filter,
                  #limit: limit,
                  #afterCursor: afterCursor,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ArchiveSearchResult>);

  @override
  _i6.Future<void> permanentlyDeleteArchive(_i10.ArchiveId? archivedChatId) =>
      (super.noSuchMethod(
            Invocation.method(#permanentlyDeleteArchive, [archivedChatId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.ArchiveStatistics?> getArchiveStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getArchiveStatistics, []),
            returnValue: _i6.Future<_i2.ArchiveStatistics?>.value(),
          )
          as _i6.Future<_i2.ArchiveStatistics?>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ArchiveManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockArchiveManagementService extends _i1.Mock
    implements _i15.ArchiveManagementService {
  MockArchiveManagementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i3.ArchiveUpdateEvent> get archiveUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#archiveUpdates),
            returnValue: _i6.Stream<_i3.ArchiveUpdateEvent>.empty(),
          )
          as _i6.Stream<_i3.ArchiveUpdateEvent>);

  @override
  _i6.Stream<_i3.ArchivePolicyEvent> get policyUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#policyUpdates),
            returnValue: _i6.Stream<_i3.ArchivePolicyEvent>.empty(),
          )
          as _i6.Stream<_i3.ArchivePolicyEvent>);

  @override
  _i6.Stream<_i3.ArchiveMaintenanceEvent> get maintenanceUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#maintenanceUpdates),
            returnValue: _i6.Stream<_i3.ArchiveMaintenanceEvent>.empty(),
          )
          as _i6.Stream<_i3.ArchiveMaintenanceEvent>);

  @override
  _i3.ArchiveManagementConfig get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeArchiveManagementConfig_2(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i3.ArchiveManagementConfig);

  @override
  List<_i3.ArchivePolicy> get archivePolicies =>
      (super.noSuchMethod(
            Invocation.getter(#archivePolicies),
            returnValue: <_i3.ArchivePolicy>[],
          )
          as List<_i3.ArchivePolicy>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.ArchiveOperationResult> archiveChat({
    required String? chatId,
    String? reason,
    Map<String, dynamic>? metadata,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#archiveChat, [], {
              #chatId: chatId,
              #reason: reason,
              #metadata: metadata,
              #force: force,
            }),
            returnValue: _i6.Future<_i2.ArchiveOperationResult>.value(
              _FakeArchiveOperationResult_0(
                this,
                Invocation.method(#archiveChat, [], {
                  #chatId: chatId,
                  #reason: reason,
                  #metadata: metadata,
                  #force: force,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ArchiveOperationResult>);

  @override
  _i6.Future<_i2.ArchiveOperationResult> restoreChat({
    required _i10.ArchiveId? archiveId,
    bool? overwriteExisting = false,
    String? targetChatId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreChat, [], {
              #archiveId: archiveId,
              #overwriteExisting: overwriteExisting,
              #targetChatId: targetChatId,
            }),
            returnValue: _i6.Future<_i2.ArchiveOperationResult>.value(
              _FakeArchiveOperationResult_0(
                this,
                Invocation.method(#restoreChat, [], {
                  #archiveId: archiveId,
                  #overwriteExisting: overwriteExisting,
                  #targetChatId: targetChatId,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ArchiveOperationResult>);

  @override
  _i6.Future<List<_i3.EnhancedArchiveSummary>> getEnhancedArchiveSummaries({
    _i2.ArchiveSearchFilter? filter,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEnhancedArchiveSummaries, [], {
              #filter: filter,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i6.Future<List<_i3.EnhancedArchiveSummary>>.value(
              <_i3.EnhancedArchiveSummary>[],
            ),
          )
          as _i6.Future<List<_i3.EnhancedArchiveSummary>>);

  @override
  _i6.Future<_i3.ArchivePolicyResult> applyArchivePolicies({
    List<String>? specificPolicies,
    bool? dryRun = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyArchivePolicies, [], {
              #specificPolicies: specificPolicies,
              #dryRun: dryRun,
            }),
            returnValue: _i6.Future<_i3.ArchivePolicyResult>.value(
              _FakeArchivePolicyResult_3(
                this,
                Invocation.method(#applyArchivePolicies, [], {
                  #specificPolicies: specificPolicies,
                  #dryRun: dryRun,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.ArchivePolicyResult>);

  @override
  _i6.Future<_i3.ArchiveMaintenanceResult> performMaintenance({
    Set<_i3.ArchiveMaintenanceTask>? tasks = const {},
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#performMaintenance, [], {
              #tasks: tasks,
              #force: force,
            }),
            returnValue: _i6.Future<_i3.ArchiveMaintenanceResult>.value(
              _FakeArchiveMaintenanceResult_4(
                this,
                Invocation.method(#performMaintenance, [], {
                  #tasks: tasks,
                  #force: force,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.ArchiveMaintenanceResult>);

  @override
  _i6.Future<_i3.ArchiveAnalytics> getArchiveAnalytics({
    DateTime? since,
    _i3.ArchiveAnalyticsScope? scope = _i3.ArchiveAnalyticsScope.all,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getArchiveAnalytics, [], {
              #since: since,
              #scope: scope,
            }),
            returnValue: _i6.Future<_i3.ArchiveAnalytics>.value(
              _FakeArchiveAnalytics_5(
                this,
                Invocation.method(#getArchiveAnalytics, [], {
                  #since: since,
                  #scope: scope,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.ArchiveAnalytics>);

  @override
  _i6.Future<void> updateConfiguration(_i3.ArchiveManagementConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfiguration, [config]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateArchivePolicy(_i3.ArchivePolicy? policy) =>
      (super.noSuchMethod(
            Invocation.method(#updateArchivePolicy, [policy]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeArchivePolicy(String? policyName) =>
      (super.noSuchMethod(
            Invocation.method(#removeArchivePolicy, [policyName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.ArchiveHealthStatus> getHealthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getHealthStatus, []),
            returnValue: _i6.Future<_i3.ArchiveHealthStatus>.value(
              _FakeArchiveHealthStatus_6(
                this,
                Invocation.method(#getHealthStatus, []),
              ),
            ),
          )
          as _i6.Future<_i3.ArchiveHealthStatus>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ArchiveSearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockArchiveSearchService extends _i1.Mock
    implements _i16.ArchiveSearchService {
  MockArchiveSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i4.ArchiveSearchEvent> get searchUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#searchUpdates),
            returnValue: _i6.Stream<_i4.ArchiveSearchEvent>.empty(),
          )
          as _i6.Stream<_i4.ArchiveSearchEvent>);

  @override
  _i6.Stream<_i4.SearchSuggestionEvent> get suggestionUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#suggestionUpdates),
            returnValue: _i6.Stream<_i4.SearchSuggestionEvent>.empty(),
          )
          as _i6.Stream<_i4.SearchSuggestionEvent>);

  @override
  _i4.SearchServiceConfig get configuration =>
      (super.noSuchMethod(
            Invocation.getter(#configuration),
            returnValue: _FakeSearchServiceConfig_7(
              this,
              Invocation.getter(#configuration),
            ),
          )
          as _i4.SearchServiceConfig);

  @override
  List<_i4.ArchiveSearchEntry> get searchHistory =>
      (super.noSuchMethod(
            Invocation.getter(#searchHistory),
            returnValue: <_i4.ArchiveSearchEntry>[],
          )
          as List<_i4.ArchiveSearchEntry>);

  @override
  List<_i4.SavedSearch> get savedSearches =>
      (super.noSuchMethod(
            Invocation.getter(#savedSearches),
            returnValue: <_i4.SavedSearch>[],
          )
          as List<_i4.SavedSearch>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.AdvancedSearchResult> search({
    required String? query,
    _i2.ArchiveSearchFilter? filter,
    _i4.SearchOptions? options,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #query: query,
              #filter: filter,
              #options: options,
              #limit: limit,
            }),
            returnValue: _i6.Future<_i4.AdvancedSearchResult>.value(
              _FakeAdvancedSearchResult_8(
                this,
                Invocation.method(#search, [], {
                  #query: query,
                  #filter: filter,
                  #options: options,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.AdvancedSearchResult>);

  @override
  _i6.Future<List<_i4.SearchSuggestion>> getSearchSuggestions({
    required String? partialQuery,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchSuggestions, [], {
              #partialQuery: partialQuery,
              #limit: limit,
            }),
            returnValue: _i6.Future<List<_i4.SearchSuggestion>>.value(
              <_i4.SearchSuggestion>[],
            ),
          )
          as _i6.Future<List<_i4.SearchSuggestion>>);

  @override
  _i6.Future<_i4.AdvancedSearchResult> fuzzySearch({
    required String? query,
    double? similarityThreshold = 0.7,
    _i2.ArchiveSearchFilter? filter,
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fuzzySearch, [], {
              #query: query,
              #similarityThreshold: similarityThreshold,
              #filter: filter,
              #limit: limit,
            }),
            returnValue: _i6.Future<_i4.AdvancedSearchResult>.value(
              _FakeAdvancedSearchResult_8(
                this,
                Invocation.method(#fuzzySearch, [], {
                  #query: query,
                  #similarityThreshold: similarityThreshold,
                  #filter: filter,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.AdvancedSearchResult>);

  @override
  _i6.Future<_i4.AdvancedSearchResult> searchByDateRange({
    required String? query,
    required DateTime? startDate,
    required DateTime? endDate,
    _i4.TemporalSearchMode? mode = _i4.TemporalSearchMode.archived,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchByDateRange, [], {
              #query: query,
              #startDate: startDate,
              #endDate: endDate,
              #mode: mode,
              #limit: limit,
            }),
            returnValue: _i6.Future<_i4.AdvancedSearchResult>.value(
              _FakeAdvancedSearchResult_8(
                this,
                Invocation.method(#searchByDateRange, [], {
                  #query: query,
                  #startDate: startDate,
                  #endDate: endDate,
                  #mode: mode,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.AdvancedSearchResult>);

  @override
  _i6.Future<void> saveSearch({
    required String? name,
    required String? query,
    _i2.ArchiveSearchFilter? filter,
    _i4.SearchOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveSearch, [], {
              #name: name,
              #query: query,
              #filter: filter,
              #options: options,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.AdvancedSearchResult> executeSavedSearch(
    String? savedSearchId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#executeSavedSearch, [savedSearchId]),
            returnValue: _i6.Future<_i4.AdvancedSearchResult>.value(
              _FakeAdvancedSearchResult_8(
                this,
                Invocation.method(#executeSavedSearch, [savedSearchId]),
              ),
            ),
          )
          as _i6.Future<_i4.AdvancedSearchResult>);

  @override
  _i6.Future<_i4.SearchAnalyticsReport> getSearchAnalytics({
    DateTime? since,
    _i4.SearchAnalyticsScope? scope = _i4.SearchAnalyticsScope.all,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchAnalytics, [], {
              #since: since,
              #scope: scope,
            }),
            returnValue: _i6.Future<_i4.SearchAnalyticsReport>.value(
              _FakeSearchAnalyticsReport_9(
                this,
                Invocation.method(#getSearchAnalytics, [], {
                  #since: since,
                  #scope: scope,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.SearchAnalyticsReport>);

  @override
  _i6.Future<void> updateConfiguration(_i4.SearchServiceConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfiguration, [config]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearSearchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearSearchHistory, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearCaches() => super.noSuchMethod(
    Invocation.method(#clearCaches, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> clearSavedSearches() =>
      (super.noSuchMethod(
            Invocation.method(#clearSavedSearches, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAnalytics() =>
      (super.noSuchMethod(
            Invocation.method(#clearAnalytics, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> rebuildIndexes() =>
      (super.noSuchMethod(
            Invocation.method(#rebuildIndexes, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
