// Mocks generated by Mockito 5.4.6 from annotations
// in pak_connect/test/domain/services/group_messaging_service_send_message_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:pak_connect/domain/entities/contact.dart' as _i9;
import 'package:pak_connect/domain/entities/queue_enums.dart' as _i15;
import 'package:pak_connect/domain/entities/queue_statistics.dart' as _i4;
import 'package:pak_connect/domain/entities/queued_message.dart' as _i13;
import 'package:pak_connect/domain/interfaces/i_contact_repository.dart' as _i8;
import 'package:pak_connect/domain/interfaces/i_group_repository.dart' as _i6;
import 'package:pak_connect/domain/messaging/offline_message_queue_contract.dart'
    as _i12;
import 'package:pak_connect/domain/models/contact_group.dart' as _i2;
import 'package:pak_connect/domain/models/mesh_relay_models.dart' as _i5;
import 'package:pak_connect/domain/models/security_level.dart' as _i10;
import 'package:pak_connect/domain/values/id_types.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeContactGroup_0 extends _i1.SmartFake implements _i2.ContactGroup {
  _FakeContactGroup_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageId_1 extends _i1.SmartFake implements _i3.MessageId {
  _FakeMessageId_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueueStatistics_2 extends _i1.SmartFake
    implements _i4.QueueStatistics {
  _FakeQueueStatistics_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueueSyncMessage_3 extends _i1.SmartFake
    implements _i5.QueueSyncMessage {
  _FakeQueueSyncMessage_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IGroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGroupRepository extends _i1.Mock implements _i6.IGroupRepository {
  @override
  _i7.Future<_i2.ContactGroup> createGroup(_i2.ContactGroup? group) =>
      (super.noSuchMethod(
            Invocation.method(#createGroup, [group]),
            returnValue: _i7.Future<_i2.ContactGroup>.value(
              _FakeContactGroup_0(
                this,
                Invocation.method(#createGroup, [group]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ContactGroup>.value(
              _FakeContactGroup_0(
                this,
                Invocation.method(#createGroup, [group]),
              ),
            ),
          )
          as _i7.Future<_i2.ContactGroup>);

  @override
  _i7.Future<_i2.ContactGroup?> getGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroup, [groupId]),
            returnValue: _i7.Future<_i2.ContactGroup?>.value(),
            returnValueForMissingStub: _i7.Future<_i2.ContactGroup?>.value(),
          )
          as _i7.Future<_i2.ContactGroup?>);

  @override
  _i7.Future<List<_i2.ContactGroup>> getAllGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getAllGroups, []),
            returnValue: _i7.Future<List<_i2.ContactGroup>>.value(
              <_i2.ContactGroup>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i2.ContactGroup>>.value(
              <_i2.ContactGroup>[],
            ),
          )
          as _i7.Future<List<_i2.ContactGroup>>);

  @override
  _i7.Future<void> updateGroup(_i2.ContactGroup? group) =>
      (super.noSuchMethod(
            Invocation.method(#updateGroup, [group]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGroup, [groupId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveGroupMessage(_i2.GroupMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveGroupMessage, [message]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateDeliveryStatus(
    String? messageId,
    String? memberKey,
    _i2.MessageDeliveryStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeliveryStatus, [
              messageId,
              memberKey,
              status,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.GroupMessage>> getGroupMessages(
    String? groupId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupMessages, [groupId], {#limit: limit}),
            returnValue: _i7.Future<List<_i2.GroupMessage>>.value(
              <_i2.GroupMessage>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i2.GroupMessage>>.value(
              <_i2.GroupMessage>[],
            ),
          )
          as _i7.Future<List<_i2.GroupMessage>>);

  @override
  _i7.Future<_i2.GroupMessage?> getMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessage, [messageId]),
            returnValue: _i7.Future<_i2.GroupMessage?>.value(),
            returnValueForMissingStub: _i7.Future<_i2.GroupMessage?>.value(),
          )
          as _i7.Future<_i2.GroupMessage?>);

  @override
  _i7.Future<List<_i2.ContactGroup>> getGroupsForMember(String? memberKey) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupsForMember, [memberKey]),
            returnValue: _i7.Future<List<_i2.ContactGroup>>.value(
              <_i2.ContactGroup>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i2.ContactGroup>>.value(
              <_i2.ContactGroup>[],
            ),
          )
          as _i7.Future<List<_i2.ContactGroup>>);

  @override
  _i7.Future<Map<String, int>> getStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, []),
            returnValue: _i7.Future<Map<String, int>>.value(<String, int>{}),
            returnValueForMissingStub: _i7.Future<Map<String, int>>.value(
              <String, int>{},
            ),
          )
          as _i7.Future<Map<String, int>>);
}

/// A class which mocks [IContactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIContactRepository extends _i1.Mock
    implements _i8.IContactRepository {
  @override
  _i7.Future<void> saveContact(String? publicKey, String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#saveContact, [publicKey, displayName]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i9.Contact?> getContact(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContact, [publicKey]),
            returnValue: _i7.Future<_i9.Contact?>.value(),
            returnValueForMissingStub: _i7.Future<_i9.Contact?>.value(),
          )
          as _i7.Future<_i9.Contact?>);

  @override
  _i7.Future<_i9.Contact?> getContactByUserId(_i3.UserId? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByUserId, [userId]),
            returnValue: _i7.Future<_i9.Contact?>.value(),
            returnValueForMissingStub: _i7.Future<_i9.Contact?>.value(),
          )
          as _i7.Future<_i9.Contact?>);

  @override
  _i7.Future<_i9.Contact?> getContactByPersistentKey(
    String? persistentPublicKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByPersistentKey, [
              persistentPublicKey,
            ]),
            returnValue: _i7.Future<_i9.Contact?>.value(),
            returnValueForMissingStub: _i7.Future<_i9.Contact?>.value(),
          )
          as _i7.Future<_i9.Contact?>);

  @override
  _i7.Future<_i9.Contact?> getContactByPersistentUserId(
    _i3.UserId? persistentPublicKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByPersistentUserId, [
              persistentPublicKey,
            ]),
            returnValue: _i7.Future<_i9.Contact?>.value(),
            returnValueForMissingStub: _i7.Future<_i9.Contact?>.value(),
          )
          as _i7.Future<_i9.Contact?>);

  @override
  _i7.Future<_i9.Contact?> getContactByCurrentEphemeralId(
    String? ephemeralId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByCurrentEphemeralId, [ephemeralId]),
            returnValue: _i7.Future<_i9.Contact?>.value(),
            returnValueForMissingStub: _i7.Future<_i9.Contact?>.value(),
          )
          as _i7.Future<_i9.Contact?>);

  @override
  _i7.Future<_i9.Contact?> getContactByAnyId(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByAnyId, [identifier]),
            returnValue: _i7.Future<_i9.Contact?>.value(),
            returnValueForMissingStub: _i7.Future<_i9.Contact?>.value(),
          )
          as _i7.Future<_i9.Contact?>);

  @override
  _i7.Future<Map<String, _i9.Contact>> getAllContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContacts, []),
            returnValue: _i7.Future<Map<String, _i9.Contact>>.value(
              <String, _i9.Contact>{},
            ),
            returnValueForMissingStub:
                _i7.Future<Map<String, _i9.Contact>>.value(
                  <String, _i9.Contact>{},
                ),
          )
          as _i7.Future<Map<String, _i9.Contact>>);

  @override
  _i7.Future<bool> deleteContact(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#deleteContact, [publicKey]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> markContactVerified(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#markContactVerified, [publicKey]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateNoiseSession({
    required String? publicKey,
    required String? noisePublicKey,
    required String? sessionState,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoiseSession, [], {
              #publicKey: publicKey,
              #noisePublicKey: noisePublicKey,
              #sessionState: sessionState,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateContactSecurityLevel(
    String? publicKey,
    _i10.SecurityLevel? newLevel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateContactSecurityLevel, [
              publicKey,
              newLevel,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateContactEphemeralId(
    String? publicKey,
    String? newEphemeralId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateContactEphemeralId, [
              publicKey,
              newEphemeralId,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i10.SecurityLevel> getContactSecurityLevel(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactSecurityLevel, [publicKey]),
            returnValue: _i7.Future<_i10.SecurityLevel>.value(
              _i10.SecurityLevel.low,
            ),
            returnValueForMissingStub: _i7.Future<_i10.SecurityLevel>.value(
              _i10.SecurityLevel.low,
            ),
          )
          as _i7.Future<_i10.SecurityLevel>);

  @override
  _i7.Future<void> downgradeSecurityForDeletedContact(
    String? publicKey,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downgradeSecurityForDeletedContact, [
              publicKey,
              reason,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> upgradeContactSecurity(
    String? publicKey,
    _i10.SecurityLevel? newLevel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeContactSecurity, [publicKey, newLevel]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> resetContactSecurity(String? publicKey, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#resetContactSecurity, [publicKey, reason]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> saveContactWithSecurity(
    String? publicKey,
    String? displayName,
    _i10.SecurityLevel? securityLevel, {
    String? currentEphemeralId,
    String? persistentPublicKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveContactWithSecurity,
              [publicKey, displayName, securityLevel],
              {
                #currentEphemeralId: currentEphemeralId,
                #persistentPublicKey: persistentPublicKey,
              },
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheSharedSecret(String? publicKey, String? sharedSecret) =>
      (super.noSuchMethod(
            Invocation.method(#cacheSharedSecret, [publicKey, sharedSecret]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getCachedSharedSecret(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSharedSecret, [publicKey]),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> cacheSharedSeedBytes(
    String? publicKey,
    _i11.Uint8List? seedBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheSharedSeedBytes, [publicKey, seedBytes]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i11.Uint8List?> getCachedSharedSeedBytes(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSharedSeedBytes, [publicKey]),
            returnValue: _i7.Future<_i11.Uint8List?>.value(),
            returnValueForMissingStub: _i7.Future<_i11.Uint8List?>.value(),
          )
          as _i7.Future<_i11.Uint8List?>);

  @override
  _i7.Future<void> clearCachedSecrets(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedSecrets, [publicKey]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getContactName(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#getContactName, [publicKey]),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<int> getContactCount() =>
      (super.noSuchMethod(
            Invocation.method(#getContactCount, []),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> getVerifiedContactCount() =>
      (super.noSuchMethod(
            Invocation.method(#getVerifiedContactCount, []),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<_i10.SecurityLevel, int>> getContactsBySecurityLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getContactsBySecurityLevel, []),
            returnValue: _i7.Future<Map<_i10.SecurityLevel, int>>.value(
              <_i10.SecurityLevel, int>{},
            ),
            returnValueForMissingStub:
                _i7.Future<Map<_i10.SecurityLevel, int>>.value(
                  <_i10.SecurityLevel, int>{},
                ),
          )
          as _i7.Future<Map<_i10.SecurityLevel, int>>);

  @override
  _i7.Future<int> getRecentlyActiveContactCount() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyActiveContactCount, []),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> markContactFavorite(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#markContactFavorite, [publicKey]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> unmarkContactFavorite(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#unmarkContactFavorite, [publicKey]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> toggleContactFavorite(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#toggleContactFavorite, [publicKey]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<_i9.Contact>> getFavoriteContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteContacts, []),
            returnValue: _i7.Future<List<_i9.Contact>>.value(<_i9.Contact>[]),
            returnValueForMissingStub: _i7.Future<List<_i9.Contact>>.value(
              <_i9.Contact>[],
            ),
          )
          as _i7.Future<List<_i9.Contact>>);

  @override
  _i7.Future<int> getFavoriteContactCount() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteContactCount, []),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<bool> isContactFavorite(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#isContactFavorite, [publicKey]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [OfflineMessageQueueContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineMessageQueueContract extends _i1.Mock
    implements _i12.OfflineMessageQueueContract {
  @override
  set onMessageQueued(dynamic Function(_i13.QueuedMessage)? callback) =>
      super.noSuchMethod(
        Invocation.setter(#onMessageQueued, callback),
        returnValueForMissingStub: null,
      );

  @override
  set onMessageDelivered(dynamic Function(_i13.QueuedMessage)? callback) =>
      super.noSuchMethod(
        Invocation.setter(#onMessageDelivered, callback),
        returnValueForMissingStub: null,
      );

  @override
  set onMessageFailed(dynamic Function(_i13.QueuedMessage, String)? callback) =>
      super.noSuchMethod(
        Invocation.setter(#onMessageFailed, callback),
        returnValueForMissingStub: null,
      );

  @override
  set onStatsUpdated(dynamic Function(_i4.QueueStatistics)? callback) =>
      super.noSuchMethod(
        Invocation.setter(#onStatsUpdated, callback),
        returnValueForMissingStub: null,
      );

  @override
  set onSendMessage(dynamic Function(String)? callback) => super.noSuchMethod(
    Invocation.setter(#onSendMessage, callback),
    returnValueForMissingStub: null,
  );

  @override
  set onConnectivityCheck(dynamic Function()? callback) => super.noSuchMethod(
    Invocation.setter(#onConnectivityCheck, callback),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> initialize({
    dynamic Function(_i13.QueuedMessage)? onMessageQueued,
    dynamic Function(_i13.QueuedMessage)? onMessageDelivered,
    dynamic Function(_i13.QueuedMessage, String)? onMessageFailed,
    dynamic Function(_i4.QueueStatistics)? onStatsUpdated,
    dynamic Function(String)? onSendMessage,
    dynamic Function()? onConnectivityCheck,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #onMessageQueued: onMessageQueued,
              #onMessageDelivered: onMessageDelivered,
              #onMessageFailed: onMessageFailed,
              #onStatsUpdated: onStatsUpdated,
              #onSendMessage: onSendMessage,
              #onConnectivityCheck: onConnectivityCheck,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String> queueMessage({
    required String? chatId,
    required String? content,
    required String? recipientPublicKey,
    required String? senderPublicKey,
    _i13.MessagePriority? priority = _i13.MessagePriority.normal,
    String? replyToMessageId,
    List<String>? attachments = const [],
    bool? isRelayMessage = false,
    _i5.RelayMetadata? relayMetadata,
    String? originalMessageId,
    String? relayNodeId,
    String? messageHash,
    bool? persistToStorage = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queueMessage, [], {
              #chatId: chatId,
              #content: content,
              #recipientPublicKey: recipientPublicKey,
              #senderPublicKey: senderPublicKey,
              #priority: priority,
              #replyToMessageId: replyToMessageId,
              #attachments: attachments,
              #isRelayMessage: isRelayMessage,
              #relayMetadata: relayMetadata,
              #originalMessageId: originalMessageId,
              #relayNodeId: relayNodeId,
              #messageHash: messageHash,
              #persistToStorage: persistToStorage,
            }),
            returnValue: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#queueMessage, [], {
                  #chatId: chatId,
                  #content: content,
                  #recipientPublicKey: recipientPublicKey,
                  #senderPublicKey: senderPublicKey,
                  #priority: priority,
                  #replyToMessageId: replyToMessageId,
                  #attachments: attachments,
                  #isRelayMessage: isRelayMessage,
                  #relayMetadata: relayMetadata,
                  #originalMessageId: originalMessageId,
                  #relayNodeId: relayNodeId,
                  #messageHash: messageHash,
                  #persistToStorage: persistToStorage,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#queueMessage, [], {
                  #chatId: chatId,
                  #content: content,
                  #recipientPublicKey: recipientPublicKey,
                  #senderPublicKey: senderPublicKey,
                  #priority: priority,
                  #replyToMessageId: replyToMessageId,
                  #attachments: attachments,
                  #isRelayMessage: isRelayMessage,
                  #relayMetadata: relayMetadata,
                  #originalMessageId: originalMessageId,
                  #relayNodeId: relayNodeId,
                  #messageHash: messageHash,
                  #persistToStorage: persistToStorage,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i3.MessageId> queueMessageWithIds({
    required _i3.ChatId? chatId,
    required String? content,
    required _i3.ChatId? recipientId,
    required _i3.ChatId? senderId,
    _i13.MessagePriority? priority = _i13.MessagePriority.normal,
    _i3.MessageId? replyToMessageId,
    List<String>? attachments = const [],
    bool? isRelayMessage = false,
    _i5.RelayMetadata? relayMetadata,
    String? originalMessageId,
    String? relayNodeId,
    String? messageHash,
    bool? persistToStorage = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queueMessageWithIds, [], {
              #chatId: chatId,
              #content: content,
              #recipientId: recipientId,
              #senderId: senderId,
              #priority: priority,
              #replyToMessageId: replyToMessageId,
              #attachments: attachments,
              #isRelayMessage: isRelayMessage,
              #relayMetadata: relayMetadata,
              #originalMessageId: originalMessageId,
              #relayNodeId: relayNodeId,
              #messageHash: messageHash,
              #persistToStorage: persistToStorage,
            }),
            returnValue: _i7.Future<_i3.MessageId>.value(
              _FakeMessageId_1(
                this,
                Invocation.method(#queueMessageWithIds, [], {
                  #chatId: chatId,
                  #content: content,
                  #recipientId: recipientId,
                  #senderId: senderId,
                  #priority: priority,
                  #replyToMessageId: replyToMessageId,
                  #attachments: attachments,
                  #isRelayMessage: isRelayMessage,
                  #relayMetadata: relayMetadata,
                  #originalMessageId: originalMessageId,
                  #relayNodeId: relayNodeId,
                  #messageHash: messageHash,
                  #persistToStorage: persistToStorage,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.MessageId>.value(
              _FakeMessageId_1(
                this,
                Invocation.method(#queueMessageWithIds, [], {
                  #chatId: chatId,
                  #content: content,
                  #recipientId: recipientId,
                  #senderId: senderId,
                  #priority: priority,
                  #replyToMessageId: replyToMessageId,
                  #attachments: attachments,
                  #isRelayMessage: isRelayMessage,
                  #relayMetadata: relayMetadata,
                  #originalMessageId: originalMessageId,
                  #relayNodeId: relayNodeId,
                  #messageHash: messageHash,
                  #persistToStorage: persistToStorage,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.MessageId>);

  @override
  _i7.Future<int> removeMessagesForChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMessagesForChat, [chatId]),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> setOnline() =>
      (super.noSuchMethod(
            Invocation.method(#setOnline, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void setOffline() => super.noSuchMethod(
    Invocation.method(#setOffline, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> markMessageDelivered(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageDelivered, [messageId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markMessageFailed(String? messageId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageFailed, [messageId, reason]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i4.QueueStatistics getStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, []),
            returnValue: _FakeQueueStatistics_2(
              this,
              Invocation.method(#getStatistics, []),
            ),
            returnValueForMissingStub: _FakeQueueStatistics_2(
              this,
              Invocation.method(#getStatistics, []),
            ),
          )
          as _i4.QueueStatistics);

  @override
  _i7.Future<void> retryFailedMessages() =>
      (super.noSuchMethod(
            Invocation.method(#retryFailedMessages, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> retryFailedMessagesForChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#retryFailedMessagesForChat, [chatId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearQueue() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueue, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<_i13.QueuedMessage> getMessagesByStatus(
    _i15.QueuedMessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByStatus, [status]),
            returnValue: <_i13.QueuedMessage>[],
            returnValueForMissingStub: <_i13.QueuedMessage>[],
          )
          as List<_i13.QueuedMessage>);

  @override
  _i13.QueuedMessage? getMessageById(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [messageId]),
            returnValueForMissingStub: null,
          )
          as _i13.QueuedMessage?);

  @override
  List<_i13.QueuedMessage> getPendingMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingMessages, []),
            returnValue: <_i13.QueuedMessage>[],
            returnValueForMissingStub: <_i13.QueuedMessage>[],
          )
          as List<_i13.QueuedMessage>);

  @override
  _i7.Future<void> removeMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMessage, [messageId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> flushQueueForPeer(String? peerPublicKey) =>
      (super.noSuchMethod(
            Invocation.method(#flushQueueForPeer, [peerPublicKey]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> changePriority(
    String? messageId,
    _i13.MessagePriority? newPriority,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePriority, [messageId, newPriority]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  String calculateQueueHash({bool? forceRecalculation = false}) =>
      (super.noSuchMethod(
            Invocation.method(#calculateQueueHash, [], {
              #forceRecalculation: forceRecalculation,
            }),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#calculateQueueHash, [], {
                #forceRecalculation: forceRecalculation,
              }),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#calculateQueueHash, [], {
                #forceRecalculation: forceRecalculation,
              }),
            ),
          )
          as String);

  @override
  _i5.QueueSyncMessage createSyncMessage(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#createSyncMessage, [nodeId]),
            returnValue: _FakeQueueSyncMessage_3(
              this,
              Invocation.method(#createSyncMessage, [nodeId]),
            ),
            returnValueForMissingStub: _FakeQueueSyncMessage_3(
              this,
              Invocation.method(#createSyncMessage, [nodeId]),
            ),
          )
          as _i5.QueueSyncMessage);

  @override
  bool needsSynchronization(String? otherQueueHash) =>
      (super.noSuchMethod(
            Invocation.method(#needsSynchronization, [otherQueueHash]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> addSyncedMessage(_i13.QueuedMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#addSyncedMessage, [message]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<String> getMissingMessageIds(List<String>? otherMessageIds) =>
      (super.noSuchMethod(
            Invocation.method(#getMissingMessageIds, [otherMessageIds]),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  List<_i13.QueuedMessage> getExcessMessages(List<String>? otherMessageIds) =>
      (super.noSuchMethod(
            Invocation.method(#getExcessMessages, [otherMessageIds]),
            returnValue: <_i13.QueuedMessage>[],
            returnValueForMissingStub: <_i13.QueuedMessage>[],
          )
          as List<_i13.QueuedMessage>);

  @override
  _i7.Future<void> markMessageDeleted(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageDeleted, [messageId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool isMessageDeleted(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#isMessageDeleted, [messageId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> cleanupOldDeletedIds() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldDeletedIds, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void invalidateHashCache() => super.noSuchMethod(
    Invocation.method(#invalidateHashCache, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getPerformanceStats() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceStats, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
